// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.response;

public class Campaign extends Response {
    private String id;
    private String name;
    private User[] applicableShops;
    private Boolean isExclusive;
    private String startsAt;
    private String endsAt;
    private String pointExpiresAt;
    private Integer pointExpiresInDays;
    private Integer priority;
    private String description;
    private User bearPointShop;
    private PrivateMoney privateMoney;
    private String pointCalculationRule;
    private String pointCalculationRuleObject;
    private String status;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public User[] getApplicableShops() {
        return applicableShops;
    }

    public boolean isExclusive() {
        return isExclusive;
    }

    public String getStartsAt() {
        return startsAt;
    }

    public String getEndsAt() {
        return endsAt;
    }

    public String getPointExpiresAt() {
        return pointExpiresAt;
    }

    public int getPointExpiresInDays() {
        return pointExpiresInDays;
    }

    public int getPriority() {
        return priority;
    }

    public String getDescription() {
        return description;
    }

    public User getBearPointShop() {
        return bearPointShop;
    }

    public PrivateMoney getPrivateMoney() {
        return privateMoney;
    }

    public String getPointCalculationRule() {
        return pointCalculationRule;
    }

    public String getPointCalculationRuleObject() {
        return pointCalculationRuleObject;
    }

    public String getStatus() {
        return status;
    }
}

