// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.response;

public class PaginatedBills extends Response {
    private Bill[] rows;
    private Integer count;
    private Pagination pagination;

    public Bill[] getRows() {
        return rows;
    }

    public Integer getCount() {
        return count;
    }

    public Pagination getPagination() {
        return pagination;
    }
}

