// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.response;

public class Pong extends Response {
    private String pong;

    public String getPong() {
        return pong;
    }
}

