// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.BulkCreateTransaction;
import jp.pokepay.partnerapi.request.Request;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class BulkCreateTransactionTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new BulkCreateTransaction(
            "Ae43BTjYiVtdGDmgs4Vk2VUx2tI5N4bI",
            "N",
            "tWwRJ7taFGOOZNR9womkOYYXss1h0acoAUmA"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new BulkCreateTransaction(
            "Ae43BTjYiVtdGDmgs4Vk2VUx2tI5N4bI",
            "N",
            "tWwRJ7taFGOOZNR9womkOYYXss1h0acoAUmA"
        )
                .description("E9DWtANH45sfx8Sg9q1O62IQSAJ63xgskw6yfFQPcXHRn98CcSXK5Zlq5PBZ9vRV0xb");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
