// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.BulkCreateTransaction;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class BulkCreateTransactionTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new BulkCreateTransaction(
            "O2Qolq5Tmq39frKox2v",
            "4kqmO5cmq",
            "cNP9HJRYYRbzkMpqGRRcJy6Roczdv0Mgd1sr"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new BulkCreateTransaction(
            "O2Qolq5Tmq39frKox2v",
            "4kqmO5cmq",
            "cNP9HJRYYRbzkMpqGRRcJy6Roczdv0Mgd1sr"
        )
                .privateMoneyId("07fb5ce1-781b-4164-a4b6-777e407dc3af");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new BulkCreateTransaction(
            "O2Qolq5Tmq39frKox2v",
            "4kqmO5cmq",
            "cNP9HJRYYRbzkMpqGRRcJy6Roczdv0Mgd1sr"
        )
                .description("U2POaQ7Yqg2qeUatQcEXJscMb634xHMyww3nKEnST6RyTOuB4AfemtB6SrpuBXSAeoWDheXrfOZMd3ij1B67JMScW")
                .privateMoneyId("5d0abf47-973b-4637-8495-4db77bbc4dc5");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
