// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateTransactionWithCashtray;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateTransactionWithCashtrayTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateTransactionWithCashtray(
            "1070ffd2-66f2-4b4f-8f36-476bb780bbd0",
            "c47dc1c4-324c-4347-bff1-32bf49caba90"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateTransactionWithCashtray(
            "1070ffd2-66f2-4b4f-8f36-476bb780bbd0",
            "c47dc1c4-324c-4347-bff1-32bf49caba90"
        )
                .requestId("2fb6fa93-e194-484c-9782-4f290c903f91");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateTransactionWithCashtray(
            "1070ffd2-66f2-4b4f-8f36-476bb780bbd0",
            "c47dc1c4-324c-4347-bff1-32bf49caba90"
        )
                .strategy("point-preferred")
                .requestId("83d98fb8-293d-477d-895d-d4c56188db0f");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
