// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateTransaction;
import jp.pokepay.partnerapi.request.Request;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateTransactionTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateTransaction(
            "bc80248e-ee95-4dcc-9335-52f078a07d48",
            "574e958a-9cf9-48a7-ae74-f94abc515277",
            "dcc00470-c504-4783-b833-283cd11e14ab"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateTransaction(
            "bc80248e-ee95-4dcc-9335-52f078a07d48",
            "574e958a-9cf9-48a7-ae74-f94abc515277",
            "dcc00470-c504-4783-b833-283cd11e14ab"
        )
                .description("M1CxJNeX3TNDoyM9BXUYGjjxcMYU2JIFzLqyFgdF7dgK0h7z9TUMtm31cKtCxAdtfCGY0k3eTSp6ATYxQ8B7PshP2XgxPbYygqAl5CIlfSPvgBKWU4dlhP30USN7ESutiO6jNu0NXowLNLDXqDreBy2NcoyMSzyB6MN7UjIDzoi");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateTransaction(
            "bc80248e-ee95-4dcc-9335-52f078a07d48",
            "574e958a-9cf9-48a7-ae74-f94abc515277",
            "dcc00470-c504-4783-b833-283cd11e14ab"
        )
                .pointAmount(2941)
                .description("vvf7Rl7it");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new CreateTransaction(
            "bc80248e-ee95-4dcc-9335-52f078a07d48",
            "574e958a-9cf9-48a7-ae74-f94abc515277",
            "dcc00470-c504-4783-b833-283cd11e14ab"
        )
                .moneyAmount(5409)
                .pointAmount(5973)
                .description("HRxUXkFmX0WYyWa4Qlkor5fiSR6xlDHhXAAnBUzfgtn2DHbMXqPwecBgUYPz36zz0jMxxbO2nuSKSdYcp4fKBBOKPZT6RLkQnEhpnFc72q5Q4edvJOB5dA4H75Ug6MmkdohQoamIw9hTX2tgNKFuY0PIHoYv1sD3y");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
