// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateOrganization;
import jp.pokepay.partnerapi.request.Request;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateOrganizationTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .contactName("mb8mbt93MhcSpRJqub8xKVdjkqPNxwfkcISF");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankAccountHolderName("｢")
                .contactName("xLdfJE64S6n2HBmyRrc9r8yecGYnLVGYEVWE33HtGNaWiJdaUSrHp0QYP5TvL0rZwAEvjRRipdkAOIfKcTNMX3d2kNyRpeiMLZQqVv3MnWVe5OTrqZurXd1geP8lS62kKW2qhlM9itc5DSeb3xGIwH05GpF5VBVMWmPWV156StMcI92Y09dxWtM2wLSSph9UQo6PJ0Rt4DL8te9T3MwgkTKqCv4IZszNWPBFsGGkUJU");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankAccount("8040730")
                .bankAccountHolderName("-")
                .contactName("068ao1soH4f4jzZ61CAyfLzJcyvjmhCvMUIxvtRMDGVNje3z6mVpH2g6Evi5awruXC0r9UvMGA2UuggRSJ3cnTSwWaJjxcg3w0JvTLqtkJo8wIeSPU7ANGF3P35Ff");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankAccountType("other")
                .bankAccount("4468553")
                .bankAccountHolderName("\\")
                .contactName("CJawsjhtcF66KQg75U8EhUBmgXlxHYHlJhYjUUtbMh9Kbh1COa2VIJLwphUd863tJm3Kf0j95qSw0nk3GrzAiiAjLEcCaWB6CjXkWQYCGrC7qMvL79GIg4HNvhtz8ehbueiGiHJyVZdt4");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankBranchCode("458")
                .bankAccountType("current")
                .bankAccount("443")
                .bankAccountHolderName("R")
                .contactName("5ZhtocplpxN5rFU970aPyHTtV4mDpLPTewkqeJhZjBLij");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankBranchName("MXDBFKlH19am9mhXGKF1pSoqtrKH6k")
                .bankBranchCode("515")
                .bankAccountType("other")
                .bankAccount("7")
                .bankAccountHolderName("｢")
                .contactName("R7Mk90Iyr8bmCSOLzHkBj3U5SzolHJFvAJjEIaepmWmBUEN7uiY2zYPRznTGLHur6dRAVyBD3XbbQYCQ6rLb963qI1RmwmG1ROiKUeoYO");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankCode("")
                .bankBranchName("JbA5Y5OlpujL7qyqnGmP6wtOLNH9moweFpIo9dQfmnDjlOVzJbnyhCQ93Oj")
                .bankBranchCode("")
                .bankAccountType("saving")
                .bankAccount("")
                .bankAccountHolderName("ﾄ")
                .contactName("vmPr1pUhevZax3FWKrlZAr5cWe1pXWWgIbPuKbIjbpjWgqnIhjrhyiXRL6yIiHx3DSIcG5pqIhZpGMV214aNTcyq7aQvDmweQcQOAy7jpFxBkSwGWKJeEn4smPVcK0JXTzOOsjPRL1qgnC5Se2zQ3ZQiDHDyLlBxRM0CPWXCHAUHsHDQI84VKCwWvi7gxf280qLY");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "gcPtk1BxVFe",
            "Qu49O1hPUD9pBOcyGAURJG2iyBapQPlHaz1OUjNbOb1208XlK0WLcKbBow2ODro8f8FrLU1Cpohm4Hs2FKaju54IBmhDMfuspQdgG4AX0FJKl6PS8AwWcbig0AXTuQ9jSuJaPrF3uyCV7f",
            new String[]{},
            "zBgQMRvTDF@fzB5.com",
            "nMN67oi6A0@NqUg.com"
        )
                .bankName("HVI7HYi5x0NziiKcTN4")
                .bankCode("5304")
                .bankBranchName("72f1rebg7pJ4zGrI1jU9tcIuDBHnGr3IXVGZMgKcfybmexEbE7FMi9631R8f")
                .bankBranchCode("878")
                .bankAccountType("current")
                .bankAccount("75710")
                .bankAccountHolderName("ｵ")
                .contactName("NfS7zjlwQIc8LwTJ3TMiXuVxNxMXbFamJxdz4dtpTsKVxOCbZTmqQH3jLzxXTR0aNAkRq8rIR1ImekvbBwpgFdSyQmuEjVte1uAv2Ec6ctbZJo8Frjq7Fhilte6VFoQeorl5BM0dKClYS");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
