// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateCashtray;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateCashtrayTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateCashtray(
            "53a333c6-9a19-40b5-a1f1-4ca6db06acad",
            "85932866-07a3-489b-bd1a-f134c42e5db9",
            1202.0
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateCashtray(
            "53a333c6-9a19-40b5-a1f1-4ca6db06acad",
            "85932866-07a3-489b-bd1a-f134c42e5db9",
            1202.0
        )
                .expiresIn(6295);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateCashtray(
            "53a333c6-9a19-40b5-a1f1-4ca6db06acad",
            "85932866-07a3-489b-bd1a-f134c42e5db9",
            1202.0
        )
                .description("jeIbx3EkiLc5k5PdeiOG4bZosJgYpZBbnN4o5q4dfB4s7DnrNYgz0pcl9jBpvwXJQbzXA4KIyonsWPpagr6PNRMv3L1Y8x7Oc8L7PhpQh7JTUXFZzGU")
                .expiresIn(7357);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
