// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateCampaign;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateCampaignTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .budgetCapsAmount(1700450372);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(183842391);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(874521039);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .destPrivateMoneyId("f23e814e-a82e-4f59-80dc-bb55bae6305f")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1796598572);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .maxTotalPointAmount(9188)
                .destPrivateMoneyId("7d6328b7-adcd-4c7a-9e9f-67dd23876a70")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(911580421);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .maxPointAmount(1894)
                .maxTotalPointAmount(6762)
                .destPrivateMoneyId("f3920eb1-1a4c-4b8f-abaa-ffed717d04e8")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(70322009);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .existInEachProductGroups(false)
                .maxPointAmount(4046)
                .maxTotalPointAmount(6696)
                .destPrivateMoneyId("9772164e-3a70-4026-adf9-c6e26da07ab9")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(2044689677);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .minimumNumberForCombinationPurchase(1510)
                .existInEachProductGroups(false)
                .maxPointAmount(2338)
                .maxTotalPointAmount(1967)
                .destPrivateMoneyId("99794886-d6cd-4a22-8cc3-7bbe0311e856")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(563611265);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test9() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .minimumNumberOfAmount(1632)
                .minimumNumberForCombinationPurchase(5048)
                .existInEachProductGroups(true)
                .maxPointAmount(3876)
                .maxTotalPointAmount(4742)
                .destPrivateMoneyId("6c5d349e-64ca-4366-93e5-4cea52a57a67")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1700610163);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test10() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .minimumNumberOfProducts(7244)
                .minimumNumberOfAmount(1535)
                .minimumNumberForCombinationPurchase(6152)
                .existInEachProductGroups(true)
                .maxPointAmount(2440)
                .maxTotalPointAmount(3645)
                .destPrivateMoneyId("1f387825-5ded-4602-8ba4-40eafecd3a6c")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(690450299);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test11() throws ConnectionError, ProcessingError {
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .applicableShopIds(new String[]{"b65a7bf3-28b0-48cb-a485-903317b55afd","b1ec7fa7-a915-477e-b242-a1d71489a0c6","80e5aec5-79f1-415a-809d-8920e985e14e","a749002f-8524-45f5-88cf-62db5b79dbb5"})
                .minimumNumberOfProducts(2984)
                .minimumNumberOfAmount(6398)
                .minimumNumberForCombinationPurchase(6395)
                .existInEachProductGroups(false)
                .maxPointAmount(5257)
                .maxTotalPointAmount(9827)
                .destPrivateMoneyId("960e8610-debb-43e6-97d2-a44232c75436")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1381461695);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test12() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("from", "12:00");
        items.addProperty("to", "23:59");
        JsonObject items2 = new JsonObject();
        items2.addProperty("from", "12:00");
        items2.addProperty("to", "23:59");
        JsonObject items3 = new JsonObject();
        items3.addProperty("from", "12:00");
        items3.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .applicableTimeRanges(new Object[]{items,items2,items3})
                .applicableShopIds(new String[]{"3d5e4cbc-16ff-4d8c-b5d6-bcbe3009bdc5","b7a2a75e-c3ca-4f2a-b8ea-ff00ed2537e1","0fb2b705-8155-444d-92b8-4d3c3dbb96af","3269d668-bfd2-4d00-95ae-4339b446730e"})
                .minimumNumberOfProducts(4716)
                .minimumNumberOfAmount(4994)
                .minimumNumberForCombinationPurchase(9820)
                .existInEachProductGroups(true)
                .maxPointAmount(6739)
                .maxTotalPointAmount(7550)
                .destPrivateMoneyId("449fdb4e-9b6c-4bc8-b066-fb232f947115")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(504306496);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test13() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("from", "12:00");
        items.addProperty("to", "23:59");
        JsonObject items2 = new JsonObject();
        items2.addProperty("from", "12:00");
        items2.addProperty("to", "23:59");
        JsonObject items3 = new JsonObject();
        items3.addProperty("from", "12:00");
        items3.addProperty("to", "23:59");
        JsonObject items4 = new JsonObject();
        items4.addProperty("from", "12:00");
        items4.addProperty("to", "23:59");
        JsonObject items5 = new JsonObject();
        items5.addProperty("from", "12:00");
        items5.addProperty("to", "23:59");
        JsonObject items6 = new JsonObject();
        items6.addProperty("from", "12:00");
        items6.addProperty("to", "23:59");
        JsonObject items7 = new JsonObject();
        items7.addProperty("from", "12:00");
        items7.addProperty("to", "23:59");
        JsonObject items8 = new JsonObject();
        items8.addProperty("from", "12:00");
        items8.addProperty("to", "23:59");
        JsonObject items9 = new JsonObject();
        items9.addProperty("from", "12:00");
        items9.addProperty("to", "23:59");
        JsonObject items10 = new JsonObject();
        items10.addProperty("from", "12:00");
        items10.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .applicableDaysOfWeek(new Integer[]{4,2,3,4,3,2,0})
                .applicableTimeRanges(new Object[]{items,items2,items3,items4,items5,items6,items7,items8,items9,items10})
                .applicableShopIds(new String[]{"b5d2e7c3-2d0b-4cd8-9f12-ab282b1ebf04","4c9f3fe2-0e4f-4b90-9847-a53a15398a86","852d4a84-4508-4444-a753-8ec263bbdde2","9ebeac5e-aa05-4c62-83a6-99a26bbe79cb","0f2f886a-a2c2-4b21-9935-6cfae2fb2972","71f038be-b928-49b7-9dfb-1046b589e92a","24154118-403f-4e9b-9432-8915b94221bd","292ac5fc-2b8f-4d07-81b3-1ccecede96ec","58a7d8d2-58a6-440a-bbab-dba247ff3d81"})
                .minimumNumberOfProducts(8593)
                .minimumNumberOfAmount(3749)
                .minimumNumberForCombinationPurchase(9188)
                .existInEachProductGroups(true)
                .maxPointAmount(2935)
                .maxTotalPointAmount(4622)
                .destPrivateMoneyId("12037949-7f16-498b-99e4-dbad1f035a8e")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1826608299);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test14() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("product_code", "4912345678904");
        items.addProperty("classification_code", "c123");
        JsonObject items2 = new JsonObject();
        items2.addProperty("product_code", "4912345678904");
        items2.addProperty("classification_code", "c123");
        JsonObject items3 = new JsonObject();
        items3.addProperty("product_code", "4912345678904");
        items3.addProperty("classification_code", "c123");
        JsonObject items4 = new JsonObject();
        items4.addProperty("product_code", "4912345678904");
        items4.addProperty("classification_code", "c123");
        JsonObject items5 = new JsonObject();
        items5.addProperty("product_code", "4912345678904");
        items5.addProperty("classification_code", "c123");
        JsonObject items6 = new JsonObject();
        items6.addProperty("product_code", "4912345678904");
        items6.addProperty("classification_code", "c123");
        JsonObject items7 = new JsonObject();
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("classification_code", "c123");
        JsonObject items8 = new JsonObject();
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("classification_code", "c123");
        JsonObject items9 = new JsonObject();
        items9.addProperty("from", "12:00");
        items9.addProperty("to", "23:59");
        JsonObject items10 = new JsonObject();
        items10.addProperty("from", "12:00");
        items10.addProperty("to", "23:59");
        JsonObject items11 = new JsonObject();
        items11.addProperty("from", "12:00");
        items11.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .blacklistedProductRules(new Object[]{items,items2,items3,items4,items5,items6,items7,items8})
                .applicableDaysOfWeek(new Integer[]{1,1,6,0,0,0,3,5,6})
                .applicableTimeRanges(new Object[]{items9,items10,items11})
                .applicableShopIds(new String[]{"294be73b-6832-42b0-8130-6a60dfa3eed7"})
                .minimumNumberOfProducts(3385)
                .minimumNumberOfAmount(594)
                .minimumNumberForCombinationPurchase(5097)
                .existInEachProductGroups(false)
                .maxPointAmount(108)
                .maxTotalPointAmount(249)
                .destPrivateMoneyId("b4bf8a4f-9d3f-4848-bb24-11b443856f2c")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1785689387);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test15() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("product_code", "4912345678904");
        items.addProperty("is_multiply_by_count", true);
        items.addProperty("required_count", 2);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("product_code", "4912345678904");
        items2.addProperty("is_multiply_by_count", true);
        items2.addProperty("required_count", 2);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("product_code", "4912345678904");
        items3.addProperty("is_multiply_by_count", true);
        items3.addProperty("required_count", 2);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("product_code", "4912345678904");
        items4.addProperty("is_multiply_by_count", true);
        items4.addProperty("required_count", 2);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("product_code", "4912345678904");
        items5.addProperty("is_multiply_by_count", true);
        items5.addProperty("required_count", 2);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("product_code", "4912345678904");
        items6.addProperty("is_multiply_by_count", true);
        items6.addProperty("required_count", 2);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("is_multiply_by_count", true);
        items7.addProperty("required_count", 2);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("is_multiply_by_count", true);
        items8.addProperty("required_count", 2);
        JsonObject items9 = new JsonObject();
        items9.addProperty("point_amount", 5);
        items9.addProperty("point_amount_unit", "percent");
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("is_multiply_by_count", true);
        items9.addProperty("required_count", 2);
        JsonObject items10 = new JsonObject();
        items10.addProperty("point_amount", 5);
        items10.addProperty("point_amount_unit", "percent");
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("is_multiply_by_count", true);
        items10.addProperty("required_count", 2);
        JsonObject items11 = new JsonObject();
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("classification_code", "c123");
        JsonObject items12 = new JsonObject();
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("classification_code", "c123");
        JsonObject items13 = new JsonObject();
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("classification_code", "c123");
        JsonObject items14 = new JsonObject();
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("classification_code", "c123");
        JsonObject items15 = new JsonObject();
        items15.addProperty("product_code", "4912345678904");
        items15.addProperty("classification_code", "c123");
        JsonObject items16 = new JsonObject();
        items16.addProperty("product_code", "4912345678904");
        items16.addProperty("classification_code", "c123");
        JsonObject items17 = new JsonObject();
        items17.addProperty("product_code", "4912345678904");
        items17.addProperty("classification_code", "c123");
        JsonObject items18 = new JsonObject();
        items18.addProperty("from", "12:00");
        items18.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .productBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6,items7,items8,items9,items10})
                .blacklistedProductRules(new Object[]{items11,items12,items13,items14,items15,items16,items17})
                .applicableDaysOfWeek(new Integer[]{1,0,3,6})
                .applicableTimeRanges(new Object[]{items18})
                .applicableShopIds(new String[]{"acf525a2-6660-4f28-a6d6-2983e70bbcd1"})
                .minimumNumberOfProducts(2290)
                .minimumNumberOfAmount(5367)
                .minimumNumberForCombinationPurchase(6318)
                .existInEachProductGroups(true)
                .maxPointAmount(6239)
                .maxTotalPointAmount(9693)
                .destPrivateMoneyId("796323ff-10f4-44c9-9702-c02fa1e0a8b0")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(104278339);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test16() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("subject_more_than_or_equal", 1000);
        items4.addProperty("subject_less_than", 5000);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("subject_more_than_or_equal", 1000);
        items5.addProperty("subject_less_than", 5000);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("subject_more_than_or_equal", 1000);
        items6.addProperty("subject_less_than", 5000);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("is_multiply_by_count", true);
        items7.addProperty("required_count", 2);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("is_multiply_by_count", true);
        items8.addProperty("required_count", 2);
        JsonObject items9 = new JsonObject();
        items9.addProperty("point_amount", 5);
        items9.addProperty("point_amount_unit", "percent");
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("is_multiply_by_count", true);
        items9.addProperty("required_count", 2);
        JsonObject items10 = new JsonObject();
        items10.addProperty("point_amount", 5);
        items10.addProperty("point_amount_unit", "percent");
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("is_multiply_by_count", true);
        items10.addProperty("required_count", 2);
        JsonObject items11 = new JsonObject();
        items11.addProperty("point_amount", 5);
        items11.addProperty("point_amount_unit", "percent");
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("is_multiply_by_count", true);
        items11.addProperty("required_count", 2);
        JsonObject items12 = new JsonObject();
        items12.addProperty("point_amount", 5);
        items12.addProperty("point_amount_unit", "percent");
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("is_multiply_by_count", true);
        items12.addProperty("required_count", 2);
        JsonObject items13 = new JsonObject();
        items13.addProperty("point_amount", 5);
        items13.addProperty("point_amount_unit", "percent");
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("is_multiply_by_count", true);
        items13.addProperty("required_count", 2);
        JsonObject items14 = new JsonObject();
        items14.addProperty("point_amount", 5);
        items14.addProperty("point_amount_unit", "percent");
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("is_multiply_by_count", true);
        items14.addProperty("required_count", 2);
        JsonObject items15 = new JsonObject();
        items15.addProperty("point_amount", 5);
        items15.addProperty("point_amount_unit", "percent");
        items15.addProperty("product_code", "4912345678904");
        items15.addProperty("is_multiply_by_count", true);
        items15.addProperty("required_count", 2);
        JsonObject items16 = new JsonObject();
        items16.addProperty("point_amount", 5);
        items16.addProperty("point_amount_unit", "percent");
        items16.addProperty("product_code", "4912345678904");
        items16.addProperty("is_multiply_by_count", true);
        items16.addProperty("required_count", 2);
        JsonObject items17 = new JsonObject();
        items17.addProperty("product_code", "4912345678904");
        items17.addProperty("classification_code", "c123");
        JsonObject items18 = new JsonObject();
        items18.addProperty("product_code", "4912345678904");
        items18.addProperty("classification_code", "c123");
        JsonObject items19 = new JsonObject();
        items19.addProperty("product_code", "4912345678904");
        items19.addProperty("classification_code", "c123");
        JsonObject items20 = new JsonObject();
        items20.addProperty("product_code", "4912345678904");
        items20.addProperty("classification_code", "c123");
        JsonObject items21 = new JsonObject();
        items21.addProperty("from", "12:00");
        items21.addProperty("to", "23:59");
        JsonObject items22 = new JsonObject();
        items22.addProperty("from", "12:00");
        items22.addProperty("to", "23:59");
        JsonObject items23 = new JsonObject();
        items23.addProperty("from", "12:00");
        items23.addProperty("to", "23:59");
        JsonObject items24 = new JsonObject();
        items24.addProperty("from", "12:00");
        items24.addProperty("to", "23:59");
        JsonObject items25 = new JsonObject();
        items25.addProperty("from", "12:00");
        items25.addProperty("to", "23:59");
        JsonObject items26 = new JsonObject();
        items26.addProperty("from", "12:00");
        items26.addProperty("to", "23:59");
        JsonObject items27 = new JsonObject();
        items27.addProperty("from", "12:00");
        items27.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .amountBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6})
                .productBasedPointRules(new Object[]{items7,items8,items9,items10,items11,items12,items13,items14,items15,items16})
                .blacklistedProductRules(new Object[]{items17,items18,items19,items20})
                .applicableDaysOfWeek(new Integer[]{1,6,4})
                .applicableTimeRanges(new Object[]{items21,items22,items23,items24,items25,items26,items27})
                .applicableShopIds(new String[]{"d3b16bb5-c720-4e6c-b43b-12b618e2981b","51c2e620-65c2-46a4-a566-b9f83a1e941d","700900c0-00e4-4685-837c-2b5254cfab24","4bdd8a71-feff-4563-b223-63d78ae83730","5425f6f7-40a3-45dd-b823-ff92c1e8c4fd","bd8df6bc-0da7-4e82-8c23-326034e645b8","2deb6f3b-26c5-4fbe-a753-a4ec7a6ce0ae","8b1f40f7-8d1a-4cfa-9c64-61e23868310b","fe64fa62-00f0-4477-ad70-2ce196828c85","eb22359e-cc50-4e52-9d86-db87420abdaf"})
                .minimumNumberOfProducts(1927)
                .minimumNumberOfAmount(5408)
                .minimumNumberForCombinationPurchase(7055)
                .existInEachProductGroups(true)
                .maxPointAmount(2540)
                .maxTotalPointAmount(7600)
                .destPrivateMoneyId("bad5277c-0587-4faa-b691-1692b4f9ecc6")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1572445685);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test17() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("subject_more_than_or_equal", 1000);
        items4.addProperty("subject_less_than", 5000);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("subject_more_than_or_equal", 1000);
        items5.addProperty("subject_less_than", 5000);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("subject_more_than_or_equal", 1000);
        items6.addProperty("subject_less_than", 5000);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("subject_more_than_or_equal", 1000);
        items7.addProperty("subject_less_than", 5000);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("is_multiply_by_count", true);
        items8.addProperty("required_count", 2);
        JsonObject items9 = new JsonObject();
        items9.addProperty("point_amount", 5);
        items9.addProperty("point_amount_unit", "percent");
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("is_multiply_by_count", true);
        items9.addProperty("required_count", 2);
        JsonObject items10 = new JsonObject();
        items10.addProperty("point_amount", 5);
        items10.addProperty("point_amount_unit", "percent");
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("is_multiply_by_count", true);
        items10.addProperty("required_count", 2);
        JsonObject items11 = new JsonObject();
        items11.addProperty("point_amount", 5);
        items11.addProperty("point_amount_unit", "percent");
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("is_multiply_by_count", true);
        items11.addProperty("required_count", 2);
        JsonObject items12 = new JsonObject();
        items12.addProperty("point_amount", 5);
        items12.addProperty("point_amount_unit", "percent");
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("is_multiply_by_count", true);
        items12.addProperty("required_count", 2);
        JsonObject items13 = new JsonObject();
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("classification_code", "c123");
        JsonObject items14 = new JsonObject();
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("classification_code", "c123");
        JsonObject items15 = new JsonObject();
        items15.addProperty("product_code", "4912345678904");
        items15.addProperty("classification_code", "c123");
        JsonObject items16 = new JsonObject();
        items16.addProperty("product_code", "4912345678904");
        items16.addProperty("classification_code", "c123");
        JsonObject items17 = new JsonObject();
        items17.addProperty("product_code", "4912345678904");
        items17.addProperty("classification_code", "c123");
        JsonObject items18 = new JsonObject();
        items18.addProperty("product_code", "4912345678904");
        items18.addProperty("classification_code", "c123");
        JsonObject items19 = new JsonObject();
        items19.addProperty("from", "12:00");
        items19.addProperty("to", "23:59");
        JsonObject items20 = new JsonObject();
        items20.addProperty("from", "12:00");
        items20.addProperty("to", "23:59");
        JsonObject items21 = new JsonObject();
        items21.addProperty("from", "12:00");
        items21.addProperty("to", "23:59");
        JsonObject items22 = new JsonObject();
        items22.addProperty("from", "12:00");
        items22.addProperty("to", "23:59");
        JsonObject items23 = new JsonObject();
        items23.addProperty("from", "12:00");
        items23.addProperty("to", "23:59");
        JsonObject items24 = new JsonObject();
        items24.addProperty("from", "12:00");
        items24.addProperty("to", "23:59");
        JsonObject items25 = new JsonObject();
        items25.addProperty("from", "12:00");
        items25.addProperty("to", "23:59");
        JsonObject items26 = new JsonObject();
        items26.addProperty("from", "12:00");
        items26.addProperty("to", "23:59");
        JsonObject items27 = new JsonObject();
        items27.addProperty("from", "12:00");
        items27.addProperty("to", "23:59");
        JsonObject items28 = new JsonObject();
        items28.addProperty("from", "12:00");
        items28.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .subject("money")
                .amountBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6,items7})
                .productBasedPointRules(new Object[]{items8,items9,items10,items11,items12})
                .blacklistedProductRules(new Object[]{items13,items14,items15,items16,items17,items18})
                .applicableDaysOfWeek(new Integer[]{2,5,5})
                .applicableTimeRanges(new Object[]{items19,items20,items21,items22,items23,items24,items25,items26,items27,items28})
                .applicableShopIds(new String[]{"baa28525-ec66-45a2-9a18-55814d68e071"})
                .minimumNumberOfProducts(483)
                .minimumNumberOfAmount(8062)
                .minimumNumberForCombinationPurchase(3557)
                .existInEachProductGroups(false)
                .maxPointAmount(9756)
                .maxTotalPointAmount(1349)
                .destPrivateMoneyId("1d2eb9d5-0426-496c-9993-56da5155a790")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(681226633);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test18() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("product_code", "4912345678904");
        items4.addProperty("is_multiply_by_count", true);
        items4.addProperty("required_count", 2);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("product_code", "4912345678904");
        items5.addProperty("is_multiply_by_count", true);
        items5.addProperty("required_count", 2);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("product_code", "4912345678904");
        items6.addProperty("is_multiply_by_count", true);
        items6.addProperty("required_count", 2);
        JsonObject items7 = new JsonObject();
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("classification_code", "c123");
        JsonObject items8 = new JsonObject();
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("classification_code", "c123");
        JsonObject items9 = new JsonObject();
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("classification_code", "c123");
        JsonObject items10 = new JsonObject();
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("classification_code", "c123");
        JsonObject items11 = new JsonObject();
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("classification_code", "c123");
        JsonObject items12 = new JsonObject();
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("classification_code", "c123");
        JsonObject items13 = new JsonObject();
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("classification_code", "c123");
        JsonObject items14 = new JsonObject();
        items14.addProperty("from", "12:00");
        items14.addProperty("to", "23:59");
        JsonObject items15 = new JsonObject();
        items15.addProperty("from", "12:00");
        items15.addProperty("to", "23:59");
        JsonObject items16 = new JsonObject();
        items16.addProperty("from", "12:00");
        items16.addProperty("to", "23:59");
        JsonObject items17 = new JsonObject();
        items17.addProperty("from", "12:00");
        items17.addProperty("to", "23:59");
        JsonObject items18 = new JsonObject();
        items18.addProperty("from", "12:00");
        items18.addProperty("to", "23:59");
        JsonObject items19 = new JsonObject();
        items19.addProperty("from", "12:00");
        items19.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .setExclusive(false)
                .subject("all")
                .amountBasedPointRules(new Object[]{items,items2,items3})
                .productBasedPointRules(new Object[]{items4,items5,items6})
                .blacklistedProductRules(new Object[]{items7,items8,items9,items10,items11,items12,items13})
                .applicableDaysOfWeek(new Integer[]{0,2,0,0,3})
                .applicableTimeRanges(new Object[]{items14,items15,items16,items17,items18,items19})
                .applicableShopIds(new String[]{"b5f3207c-e5d2-4dba-95f6-bba4fe31b0d2","dd970de5-fecb-41d0-88dc-5bcadcb991cf","fbb004a9-ebf5-4327-a0b7-ad69bccbf868","4ad3b3d2-9c68-4cc3-aa25-af80e7a57c54","0d0bfc6b-55ee-4283-98e5-899a56045319"})
                .minimumNumberOfProducts(5370)
                .minimumNumberOfAmount(7761)
                .minimumNumberForCombinationPurchase(9453)
                .existInEachProductGroups(true)
                .maxPointAmount(2994)
                .maxTotalPointAmount(1462)
                .destPrivateMoneyId("f77b4b8c-60b6-45c4-bf33-1017ccc22392")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(693251655);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test19() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("product_code", "4912345678904");
        items3.addProperty("is_multiply_by_count", true);
        items3.addProperty("required_count", 2);
        JsonObject items4 = new JsonObject();
        items4.addProperty("product_code", "4912345678904");
        items4.addProperty("classification_code", "c123");
        JsonObject items5 = new JsonObject();
        items5.addProperty("product_code", "4912345678904");
        items5.addProperty("classification_code", "c123");
        JsonObject items6 = new JsonObject();
        items6.addProperty("product_code", "4912345678904");
        items6.addProperty("classification_code", "c123");
        JsonObject items7 = new JsonObject();
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("classification_code", "c123");
        JsonObject items8 = new JsonObject();
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("classification_code", "c123");
        JsonObject items9 = new JsonObject();
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("classification_code", "c123");
        JsonObject items10 = new JsonObject();
        items10.addProperty("from", "12:00");
        items10.addProperty("to", "23:59");
        JsonObject items11 = new JsonObject();
        items11.addProperty("from", "12:00");
        items11.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .pointExpiresInDays(1648)
                .setExclusive(false)
                .subject("all")
                .amountBasedPointRules(new Object[]{items,items2})
                .productBasedPointRules(new Object[]{items3})
                .blacklistedProductRules(new Object[]{items4,items5,items6,items7,items8,items9})
                .applicableDaysOfWeek(new Integer[]{2,4,6,6,2,2,2,4,0,3})
                .applicableTimeRanges(new Object[]{items10,items11})
                .applicableShopIds(new String[]{"0fcc8953-a3d4-4d4c-9d11-95d4839a20c3","e90df66c-52d2-474d-ab46-f519f822c8c9","40c06ee3-4a96-4393-9af5-17bc7a8f5465"})
                .minimumNumberOfProducts(895)
                .minimumNumberOfAmount(2729)
                .minimumNumberForCombinationPurchase(1531)
                .existInEachProductGroups(false)
                .maxPointAmount(9231)
                .maxTotalPointAmount(4852)
                .destPrivateMoneyId("dc72f89e-bb21-4f5e-99a1-299c50ec19a9")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(550049087);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test20() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("subject_more_than_or_equal", 1000);
        items4.addProperty("subject_less_than", 5000);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("subject_more_than_or_equal", 1000);
        items5.addProperty("subject_less_than", 5000);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("subject_more_than_or_equal", 1000);
        items6.addProperty("subject_less_than", 5000);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("subject_more_than_or_equal", 1000);
        items7.addProperty("subject_less_than", 5000);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("subject_more_than_or_equal", 1000);
        items8.addProperty("subject_less_than", 5000);
        JsonObject items9 = new JsonObject();
        items9.addProperty("point_amount", 5);
        items9.addProperty("point_amount_unit", "percent");
        items9.addProperty("subject_more_than_or_equal", 1000);
        items9.addProperty("subject_less_than", 5000);
        JsonObject items10 = new JsonObject();
        items10.addProperty("point_amount", 5);
        items10.addProperty("point_amount_unit", "percent");
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("is_multiply_by_count", true);
        items10.addProperty("required_count", 2);
        JsonObject items11 = new JsonObject();
        items11.addProperty("point_amount", 5);
        items11.addProperty("point_amount_unit", "percent");
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("is_multiply_by_count", true);
        items11.addProperty("required_count", 2);
        JsonObject items12 = new JsonObject();
        items12.addProperty("point_amount", 5);
        items12.addProperty("point_amount_unit", "percent");
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("is_multiply_by_count", true);
        items12.addProperty("required_count", 2);
        JsonObject items13 = new JsonObject();
        items13.addProperty("point_amount", 5);
        items13.addProperty("point_amount_unit", "percent");
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("is_multiply_by_count", true);
        items13.addProperty("required_count", 2);
        JsonObject items14 = new JsonObject();
        items14.addProperty("point_amount", 5);
        items14.addProperty("point_amount_unit", "percent");
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("is_multiply_by_count", true);
        items14.addProperty("required_count", 2);
        JsonObject items15 = new JsonObject();
        items15.addProperty("point_amount", 5);
        items15.addProperty("point_amount_unit", "percent");
        items15.addProperty("product_code", "4912345678904");
        items15.addProperty("is_multiply_by_count", true);
        items15.addProperty("required_count", 2);
        JsonObject items16 = new JsonObject();
        items16.addProperty("point_amount", 5);
        items16.addProperty("point_amount_unit", "percent");
        items16.addProperty("product_code", "4912345678904");
        items16.addProperty("is_multiply_by_count", true);
        items16.addProperty("required_count", 2);
        JsonObject items17 = new JsonObject();
        items17.addProperty("point_amount", 5);
        items17.addProperty("point_amount_unit", "percent");
        items17.addProperty("product_code", "4912345678904");
        items17.addProperty("is_multiply_by_count", true);
        items17.addProperty("required_count", 2);
        JsonObject items18 = new JsonObject();
        items18.addProperty("product_code", "4912345678904");
        items18.addProperty("classification_code", "c123");
        JsonObject items19 = new JsonObject();
        items19.addProperty("product_code", "4912345678904");
        items19.addProperty("classification_code", "c123");
        JsonObject items20 = new JsonObject();
        items20.addProperty("product_code", "4912345678904");
        items20.addProperty("classification_code", "c123");
        JsonObject items21 = new JsonObject();
        items21.addProperty("product_code", "4912345678904");
        items21.addProperty("classification_code", "c123");
        JsonObject items22 = new JsonObject();
        items22.addProperty("from", "12:00");
        items22.addProperty("to", "23:59");
        JsonObject items23 = new JsonObject();
        items23.addProperty("from", "12:00");
        items23.addProperty("to", "23:59");
        JsonObject items24 = new JsonObject();
        items24.addProperty("from", "12:00");
        items24.addProperty("to", "23:59");
        JsonObject items25 = new JsonObject();
        items25.addProperty("from", "12:00");
        items25.addProperty("to", "23:59");
        JsonObject items26 = new JsonObject();
        items26.addProperty("from", "12:00");
        items26.addProperty("to", "23:59");
        JsonObject items27 = new JsonObject();
        items27.addProperty("from", "12:00");
        items27.addProperty("to", "23:59");
        JsonObject items28 = new JsonObject();
        items28.addProperty("from", "12:00");
        items28.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .pointExpiresAt("2021-07-16T11:01:54.000000+09:00")
                .pointExpiresInDays(1795)
                .setExclusive(false)
                .subject("money")
                .amountBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6,items7,items8,items9})
                .productBasedPointRules(new Object[]{items10,items11,items12,items13,items14,items15,items16,items17})
                .blacklistedProductRules(new Object[]{items18,items19,items20,items21})
                .applicableDaysOfWeek(new Integer[]{0,1,6,1})
                .applicableTimeRanges(new Object[]{items22,items23,items24,items25,items26,items27,items28})
                .applicableShopIds(new String[]{"fe198bf6-cd5f-44b4-b006-44cde03e19fc","20664602-dd45-422b-aab5-3756f0f7d2f7","7cfa02ce-5c0f-4e7b-9a37-c3781ad78fdc","7e268923-9eb3-4a18-ac42-49754e0fbe3b","f0a9bc6d-3863-4209-89eb-13d35210cdaa","2a7def00-f4ea-4358-9a6c-e9532d785129","5940c132-9633-4791-aa09-aca288fad297","47509dcc-9878-46f5-b273-111db54eb5aa","9691f300-d1d9-47e3-9840-9740aa085b3c","9be325b2-e9c7-4a0f-a445-943742447b6a"})
                .minimumNumberOfProducts(8813)
                .minimumNumberOfAmount(1163)
                .minimumNumberForCombinationPurchase(2305)
                .existInEachProductGroups(false)
                .maxPointAmount(2014)
                .maxTotalPointAmount(2941)
                .destPrivateMoneyId("f04c95d5-0546-41a9-bf16-418582a3a268")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(1856534372);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test21() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("subject_more_than_or_equal", 1000);
        items4.addProperty("subject_less_than", 5000);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("subject_more_than_or_equal", 1000);
        items5.addProperty("subject_less_than", 5000);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("subject_more_than_or_equal", 1000);
        items6.addProperty("subject_less_than", 5000);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("is_multiply_by_count", true);
        items7.addProperty("required_count", 2);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("is_multiply_by_count", true);
        items8.addProperty("required_count", 2);
        JsonObject items9 = new JsonObject();
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("classification_code", "c123");
        JsonObject items10 = new JsonObject();
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("classification_code", "c123");
        JsonObject items11 = new JsonObject();
        items11.addProperty("from", "12:00");
        items11.addProperty("to", "23:59");
        JsonObject items12 = new JsonObject();
        items12.addProperty("from", "12:00");
        items12.addProperty("to", "23:59");
        JsonObject items13 = new JsonObject();
        items13.addProperty("from", "12:00");
        items13.addProperty("to", "23:59");
        JsonObject items14 = new JsonObject();
        items14.addProperty("from", "12:00");
        items14.addProperty("to", "23:59");
        JsonObject items15 = new JsonObject();
        items15.addProperty("from", "12:00");
        items15.addProperty("to", "23:59");
        JsonObject items16 = new JsonObject();
        items16.addProperty("from", "12:00");
        items16.addProperty("to", "23:59");
        JsonObject items17 = new JsonObject();
        items17.addProperty("from", "12:00");
        items17.addProperty("to", "23:59");
        JsonObject items18 = new JsonObject();
        items18.addProperty("from", "12:00");
        items18.addProperty("to", "23:59");
        JsonObject items19 = new JsonObject();
        items19.addProperty("from", "12:00");
        items19.addProperty("to", "23:59");
        JsonObject items20 = new JsonObject();
        items20.addProperty("from", "12:00");
        items20.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .status("disabled")
                .pointExpiresAt("2022-06-28T01:11:10.000000+09:00")
                .pointExpiresInDays(7097)
                .setExclusive(false)
                .subject("all")
                .amountBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6})
                .productBasedPointRules(new Object[]{items7,items8})
                .blacklistedProductRules(new Object[]{items9,items10})
                .applicableDaysOfWeek(new Integer[]{6})
                .applicableTimeRanges(new Object[]{items11,items12,items13,items14,items15,items16,items17,items18,items19,items20})
                .applicableShopIds(new String[]{"327b9011-08bf-42c4-ab12-649b5f1cca38","6b58b540-4388-4f93-8dd3-b7d031ce7d8b","bb4eeb7d-1569-4430-a065-84979382e60d","cefe6cea-b4bd-47f0-9f5e-20e87f2e9b2b","4f9b1b3c-3c13-4924-894a-58617a7461b7","808eaeaa-0b1c-493a-ba02-630d4bf06d50","a4b700b5-a971-4705-b945-dac8c9b2997a","c90d5253-134d-4782-8913-40b7259e7557","68923e22-18e3-45de-a2cb-39f2c71d5750"})
                .minimumNumberOfProducts(7568)
                .minimumNumberOfAmount(2359)
                .minimumNumberForCombinationPurchase(1077)
                .existInEachProductGroups(false)
                .maxPointAmount(4482)
                .maxTotalPointAmount(4267)
                .destPrivateMoneyId("2350f71a-da1c-42ea-87e9-b451bd1d60e0")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(15947449);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test22() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("product_code", "4912345678904");
        items3.addProperty("is_multiply_by_count", true);
        items3.addProperty("required_count", 2);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("product_code", "4912345678904");
        items4.addProperty("is_multiply_by_count", true);
        items4.addProperty("required_count", 2);
        JsonObject items5 = new JsonObject();
        items5.addProperty("product_code", "4912345678904");
        items5.addProperty("classification_code", "c123");
        JsonObject items6 = new JsonObject();
        items6.addProperty("product_code", "4912345678904");
        items6.addProperty("classification_code", "c123");
        JsonObject items7 = new JsonObject();
        items7.addProperty("product_code", "4912345678904");
        items7.addProperty("classification_code", "c123");
        JsonObject items8 = new JsonObject();
        items8.addProperty("product_code", "4912345678904");
        items8.addProperty("classification_code", "c123");
        JsonObject items9 = new JsonObject();
        items9.addProperty("product_code", "4912345678904");
        items9.addProperty("classification_code", "c123");
        JsonObject items10 = new JsonObject();
        items10.addProperty("product_code", "4912345678904");
        items10.addProperty("classification_code", "c123");
        JsonObject items11 = new JsonObject();
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("classification_code", "c123");
        JsonObject items12 = new JsonObject();
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("classification_code", "c123");
        JsonObject items13 = new JsonObject();
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("classification_code", "c123");
        JsonObject items14 = new JsonObject();
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("classification_code", "c123");
        JsonObject items15 = new JsonObject();
        items15.addProperty("from", "12:00");
        items15.addProperty("to", "23:59");
        JsonObject items16 = new JsonObject();
        items16.addProperty("from", "12:00");
        items16.addProperty("to", "23:59");
        JsonObject items17 = new JsonObject();
        items17.addProperty("from", "12:00");
        items17.addProperty("to", "23:59");
        JsonObject items18 = new JsonObject();
        items18.addProperty("from", "12:00");
        items18.addProperty("to", "23:59");
        JsonObject items19 = new JsonObject();
        items19.addProperty("from", "12:00");
        items19.addProperty("to", "23:59");
        JsonObject items20 = new JsonObject();
        items20.addProperty("from", "12:00");
        items20.addProperty("to", "23:59");
        JsonObject items21 = new JsonObject();
        items21.addProperty("from", "12:00");
        items21.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .description("oQrHnQE5gwL")
                .status("disabled")
                .pointExpiresAt("2022-03-04T02:45:11.000000+09:00")
                .pointExpiresInDays(6390)
                .setExclusive(false)
                .subject("all")
                .amountBasedPointRules(new Object[]{items,items2})
                .productBasedPointRules(new Object[]{items3,items4})
                .blacklistedProductRules(new Object[]{items5,items6,items7,items8,items9,items10,items11,items12,items13,items14})
                .applicableDaysOfWeek(new Integer[]{5,5,2,4,6})
                .applicableTimeRanges(new Object[]{items15,items16,items17,items18,items19,items20,items21})
                .applicableShopIds(new String[]{"eb8a911c-92c2-4cd0-bf02-e56b61228c9e"})
                .minimumNumberOfProducts(1520)
                .minimumNumberOfAmount(9644)
                .minimumNumberForCombinationPurchase(2025)
                .existInEachProductGroups(true)
                .maxPointAmount(4496)
                .maxTotalPointAmount(7818)
                .destPrivateMoneyId("e7bc571f-0046-4588-ad86-fa46292e9991")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(684942059);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test23() throws ConnectionError, ProcessingError {
        JsonObject items = new JsonObject();
        items.addProperty("point_amount", 5);
        items.addProperty("point_amount_unit", "percent");
        items.addProperty("subject_more_than_or_equal", 1000);
        items.addProperty("subject_less_than", 5000);
        JsonObject items2 = new JsonObject();
        items2.addProperty("point_amount", 5);
        items2.addProperty("point_amount_unit", "percent");
        items2.addProperty("subject_more_than_or_equal", 1000);
        items2.addProperty("subject_less_than", 5000);
        JsonObject items3 = new JsonObject();
        items3.addProperty("point_amount", 5);
        items3.addProperty("point_amount_unit", "percent");
        items3.addProperty("subject_more_than_or_equal", 1000);
        items3.addProperty("subject_less_than", 5000);
        JsonObject items4 = new JsonObject();
        items4.addProperty("point_amount", 5);
        items4.addProperty("point_amount_unit", "percent");
        items4.addProperty("subject_more_than_or_equal", 1000);
        items4.addProperty("subject_less_than", 5000);
        JsonObject items5 = new JsonObject();
        items5.addProperty("point_amount", 5);
        items5.addProperty("point_amount_unit", "percent");
        items5.addProperty("subject_more_than_or_equal", 1000);
        items5.addProperty("subject_less_than", 5000);
        JsonObject items6 = new JsonObject();
        items6.addProperty("point_amount", 5);
        items6.addProperty("point_amount_unit", "percent");
        items6.addProperty("subject_more_than_or_equal", 1000);
        items6.addProperty("subject_less_than", 5000);
        JsonObject items7 = new JsonObject();
        items7.addProperty("point_amount", 5);
        items7.addProperty("point_amount_unit", "percent");
        items7.addProperty("subject_more_than_or_equal", 1000);
        items7.addProperty("subject_less_than", 5000);
        JsonObject items8 = new JsonObject();
        items8.addProperty("point_amount", 5);
        items8.addProperty("point_amount_unit", "percent");
        items8.addProperty("subject_more_than_or_equal", 1000);
        items8.addProperty("subject_less_than", 5000);
        JsonObject items9 = new JsonObject();
        items9.addProperty("point_amount", 5);
        items9.addProperty("point_amount_unit", "percent");
        items9.addProperty("subject_more_than_or_equal", 1000);
        items9.addProperty("subject_less_than", 5000);
        JsonObject items10 = new JsonObject();
        items10.addProperty("point_amount", 5);
        items10.addProperty("point_amount_unit", "percent");
        items10.addProperty("subject_more_than_or_equal", 1000);
        items10.addProperty("subject_less_than", 5000);
        JsonObject items11 = new JsonObject();
        items11.addProperty("point_amount", 5);
        items11.addProperty("point_amount_unit", "percent");
        items11.addProperty("product_code", "4912345678904");
        items11.addProperty("is_multiply_by_count", true);
        items11.addProperty("required_count", 2);
        JsonObject items12 = new JsonObject();
        items12.addProperty("product_code", "4912345678904");
        items12.addProperty("classification_code", "c123");
        JsonObject items13 = new JsonObject();
        items13.addProperty("product_code", "4912345678904");
        items13.addProperty("classification_code", "c123");
        JsonObject items14 = new JsonObject();
        items14.addProperty("product_code", "4912345678904");
        items14.addProperty("classification_code", "c123");
        JsonObject items15 = new JsonObject();
        items15.addProperty("from", "12:00");
        items15.addProperty("to", "23:59");
        JsonObject items16 = new JsonObject();
        items16.addProperty("from", "12:00");
        items16.addProperty("to", "23:59");
        JsonObject items17 = new JsonObject();
        items17.addProperty("from", "12:00");
        items17.addProperty("to", "23:59");
        JsonObject items18 = new JsonObject();
        items18.addProperty("from", "12:00");
        items18.addProperty("to", "23:59");
        JsonObject items19 = new JsonObject();
        items19.addProperty("from", "12:00");
        items19.addProperty("to", "23:59");
        JsonObject applicable_account_metadata = new JsonObject();
        applicable_account_metadata.addProperty("key", "sex");
        applicable_account_metadata.addProperty("value", "male");
        JsonObject applicable_transaction_metadata = new JsonObject();
        applicable_transaction_metadata.addProperty("key", "rank");
        applicable_transaction_metadata.addProperty("value", "bronze");
        Request request = new CreateCampaign(
            "Z9trjCZaDNgMtUgeVk3oY0bNuUK4tBUtkAb5qt5hL5oQTMjMFYNLCLWzvO2z2NwyZolZqos0mzCYFG64NJ97qrcJ8Fm7zHnIb850EkKwKFl2BhFFpPRTHA2BLugx0FNKxutdKGGeZAdBi3tkTcaaNPV2cSIPQDJuoc1PoXbtnSK9kFTbSPSPxco42SxNuBNjqMeNo9HKjvvqkETAwPklZTAZPcVhRkwo8od",
            "45f94fb5-a30b-4190-9146-9f5bde886e4a",
            "2022-09-03T14:51:57.000000+09:00",
            "2023-12-15T03:40:33.000000+09:00",
            8701,
            "payment"
        )
                .bearPointShopId("94d9d8bd-b9e7-4a57-8133-5c32dd3a4dff")
                .description("58b0h7Y0xHM3wlHJjbeq9IRDf084I1lCHy0FvKhTZ4abDNOfPOeZ8a7M28tLyIf8Xj8xgFH4ZngBE5pioZjs6zVEtTtQUduK4Ba6dNohRUSyQdYRJAnNUYS4y")
                .status("disabled")
                .pointExpiresAt("2022-12-01T10:21:51.000000+09:00")
                .pointExpiresInDays(8701)
                .setExclusive(false)
                .subject("all")
                .amountBasedPointRules(new Object[]{items,items2,items3,items4,items5,items6,items7,items8,items9,items10})
                .productBasedPointRules(new Object[]{items11})
                .blacklistedProductRules(new Object[]{items12,items13,items14})
                .applicableDaysOfWeek(new Integer[]{4,4,0})
                .applicableTimeRanges(new Object[]{items15,items16,items17,items18,items19})
                .applicableShopIds(new String[]{"633ab36c-5f99-4a0d-ad73-f27eaa9160b0","4825f24a-60e0-4f54-b565-5064e24fd8b2","10386c1b-f66f-4e19-b4d4-0c0151efcb42","605d3edc-ae2d-4b90-a101-5ad379bbb0d9","7093dcd7-701d-4c3d-a9b6-e842d285d616","6f7b4349-1295-413c-97b1-268e056f3147","60786b0b-942d-4771-84ac-a205c78d6034"})
                .minimumNumberOfProducts(5399)
                .minimumNumberOfAmount(748)
                .minimumNumberForCombinationPurchase(7693)
                .existInEachProductGroups(false)
                .maxPointAmount(6515)
                .maxTotalPointAmount(1339)
                .destPrivateMoneyId("688339c5-8ea6-4699-a9d3-e61334ce5505")
                .applicableAccountMetadata(applicable_account_metadata)
                .applicableTransactionMetadata(applicable_transaction_metadata)
                .budgetCapsAmount(724297350);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
