// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateCustomerAccount;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateCustomerAccountTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateCustomerAccount(
            "470453b2-f44b-45ce-a5c1-c85d2b8783f8"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateCustomerAccount(
            "470453b2-f44b-45ce-a5c1-c85d2b8783f8"
        )
                .externalId("MusYOf3GWmUnXwLz54BHIlEA9iDnHsLVt6aQpKOr");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateCustomerAccount(
            "470453b2-f44b-45ce-a5c1-c85d2b8783f8"
        )
                .accountName("Jj3tUgj1o9hj9PLJdzv0ZN1dXvT6QCmKlaG4j0EqBQ3f0ayZOe30YVRilDn8VfhEtyUb9Zsw03s7If4N8yNEnGVHYeqLYOASFf3MCAPMe3JYb2ZdLObPzknF2iydp6nXf6syPW89V0GGGj7")
                .externalId("4kINFMW6qerFszGc");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new CreateCustomerAccount(
            "470453b2-f44b-45ce-a5c1-c85d2b8783f8"
        )
                .userName("n5HGIwKbBSWO96S0Gn1Zp6PMJZevVIZ132bE1xbD0ehKjJelKoEeZuMDoibLOgklz0qm0JSGDAHe8zqh6C2mn61zeglzI7Pmz7j4mE30TblUr1DanB4y52IkfijVMMDuxaY4zSqJSo7rVnLk3VGx9XJhcKogG8VbeHj4JcmsfhmqCsDxLgtZU4RWBHCa6Op40lNE")
                .accountName("411bcWrlozWs992qTOCL2ISnTsYiFeVWS00l5PJ2Hq74ENcE7a1BKH20TMnc6ltHOTEKxdWZcajRdZ8P8WyEsiKDwCNIIBmT8tT2sloKIJwfEbLhfkggRdgLdE2dACKTJxoYzMlAmn1oWR94eeMAe44ENN5Ktv3yTFHX4sKstdHsPaTaTt7qqIOt4KJDRWA5QnxPGiz4yArtdjX")
                .externalId("dQ8d6tJ0b4yt2");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
