// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.CreateOrganization;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CreateOrganizationTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .contactName("SoRCKxxDEWQZO9yz4Mc4BWxPS7UaVHpVi4pZYZOGKLSewvJuaN97ObUNQZ0A0Rwk2Z2omGatDjCcJfOMaGd4kHySUJYrKI48UyLazcda");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankAccountHolderName("R")
                .contactName("9M9b56VUQzIG7Yr7fsBnFuG56tOVY8vi9Z9lrbTGfh4QbdPS2DfLew9jsvLcXjFRqAsdyU0EjzFGdoCEVoN09yrlyTlHcxkp2hdiJWs8");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankAccount("116767")
                .bankAccountHolderName("8")
                .contactName("zZW75gRDgWRTNwobRsB1baR1aePdc9fGHLcwyelAg5Jr7zEeO7");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankAccountType("other")
                .bankAccount("89874")
                .bankAccountHolderName(",")
                .contactName("43AIOVakyq8QHWKNric3MBQYWsKtvnxoQJLloM94TQVFchk");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankBranchCode("165")
                .bankAccountType("saving")
                .bankAccount("300")
                .bankAccountHolderName("ﾗ")
                .contactName("ZUH2UsKCxnRcuSoLNAly4QR5kzfucn7LZFZwhy5RI");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankBranchName("GwbFSZ2qU3L")
                .bankBranchCode("624")
                .bankAccountType("saving")
                .bankAccount("5")
                .bankAccountHolderName("\\")
                .contactName("3O9wlyQ0TWfR4Gx21zM7WIQGDsPsJyAShBlCJPjtVj6RA58jW2j8noWbhryHKQAP2bBeZkmIh2UeN7Z047tEp9MnaMKkPTTOh4KlFXKgtixsqVTYrrSHZ1a0tz4EzkuhUCHWp85qyAYWUJWst1yIlHOt0XiM6Qkur8SbZd3wcuCesxkTgeUlIAlQvL5t780R8L5VrLxzRQlVu0ZdkmHWdPUiVDqeHPcQVtlOjSB31Mxq8SXpxSHJRZi52y7");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankCode("4615")
                .bankBranchName("klIR5ig74Fkbtbb0Sl")
                .bankBranchCode("219")
                .bankAccountType("other")
                .bankAccount("7948")
                .bankAccountHolderName("\\")
                .contactName("Hxi6f0cuW1ZhxLtCHCm7yUfJm7Fg98YgjSKRGLQpNx8ciNrKweGJtnGqdSp9");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new CreateOrganization(
            "T6b0IY83jSy9CLjq8yjjxInoBnLVw5N",
            "xHP7CI9Yb5tOQ2qp6BlopujNmJIuVKWvjUjC0u3f2Lo9NqlV6uXM4yE9kd7lV6QKkz6REzoI7cZYW4c0GyNh6EpQVqX4KE4B5KRDxSSppVORQLy6PO73cHGKqjz0v27dHE8reh9b3v7zqeYS2n0EGsPPbvQvYkA",
            new String[]{"f53e5ac2-eea9-46ca-b71a-e17761216ea0"},
            "mgCWNKDP1e@nxAK.com",
            "ZBD2FhNoFZ@KIbA.com"
        )
                .bankName("ci6D0iGddOVzLT6tirwJLurByrAGwszVwlQAuTXTWtKg2YB5Y")
                .bankCode("")
                .bankBranchName("VquVYsbDyy")
                .bankBranchCode("292")
                .bankAccountType("other")
                .bankAccount("534")
                .bankAccountHolderName(".")
                .contactName("qoj4yKOsEPCrpQPvSjUDltH57ysDpO4lTbJ9dqwKn5NSHIJ7mbc5qbOnYCYxA4AjI47p6qtIsaCpt80GzH1FRWe6zLcwMHaeJ");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
