// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.GetAccountTransferSummary;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class GetAccountTransferSummaryTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new GetAccountTransferSummary(
            "95626e10-7ff6-4628-b94c-565d8306a14f"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new GetAccountTransferSummary(
            "95626e10-7ff6-4628-b94c-565d8306a14f"
        )
                .transferTypes(new String[]{"use-coupon","refund-exchange-outflow","refund-campaign","payment","refund-coupon","campaign-topup","refund-payment","topup","exchange-outflow","exchange-inflow","refund-exchange-inflow","refund-topup"});
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new GetAccountTransferSummary(
            "95626e10-7ff6-4628-b94c-565d8306a14f"
        )
                .to("2024-02-11T20:15:48.000000Z")
                .transferTypes(new String[]{"exchange-inflow","campaign-topup","refund-exchange-outflow","use-coupon","refund-campaign","refund-topup","payment","refund-coupon"});
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new GetAccountTransferSummary(
            "95626e10-7ff6-4628-b94c-565d8306a14f"
        )
                .from("2022-07-04T12:30:27.000000Z")
                .to("2022-11-07T15:21:05.000000Z")
                .transferTypes(new String[]{"campaign-topup","payment","exchange-outflow","exchange-inflow","refund-payment","refund-topup","refund-exchange-inflow"});
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
