// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.ListTransactions;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ListTransactionsTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions();
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .description("fCbULrspxhijGkLdZcXfDQmoigVp5ZlUvZaUIbfsOJBElASmQ7WYeFduOUkc7UofOIafKWeuzBVt9Luwm8F3FlC2xGmbs8tD4");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .types(new String[]{"topup","exchange_inflow","cashback","expire"})
                .description("ohsO6gau0kMFyNAuwG0DNNcWoJDOSOW6RQ99EWvfWSjk5qYZ8CRSr6GNJovjQC79MzhSGvlKF8vqh7QUJ1ZVxpyubxBvfw27");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .setModified(false)
                .types(new String[]{"exchange_outflow","payment"})
                .description("Eh1dq8k7rbcYMcaUGJhNZ4nnidVlZWRPwu94mct7aAqYs3M2w9ETcN6SMBQEU6LMSM7bUaSvwUmZ0");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .privateMoneyId("356612e0-1b70-4623-acf8-dae9d8ae0f0e")
                .setModified(true)
                .types(new String[]{"cashback","expire","exchange_inflow","payment","exchange_outflow","topup"})
                .description("k6bX0EuX1IDaIvFDG3mReQxJsb4dEd");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .organizationCode("-H")
                .privateMoneyId("89b84724-26dd-4fdc-9077-bffea865b9b9")
                .setModified(true)
                .types(new String[]{"topup","payment","exchange_outflow","exchange_inflow","cashback"})
                .description("hNpc7KMvOBwu0Ss5HuyfOFpIOqOmYJx9NWNBnqkhjHZ4q5yZJzloyWTIBMba3MeGEPz19AygnpiPtRxElPRJgvwWQjS01G8AYls3Ksv9DrmMGHND");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .transactionId("HFWsSN")
                .organizationCode("rN3h-G--sW-g0-f3-")
                .privateMoneyId("8114a086-1666-45b1-8297-5da371e3be50")
                .setModified(false)
                .types(new String[]{"cashback","topup","exchange_outflow","expire","exchange_inflow","payment"})
                .description("zlVwRWF35eRlJmIXumGsfoQ0SmS4pVNEftW9");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .terminalId("9e0e8ab6-00d1-470d-817b-91f1114db35a")
                .transactionId("55LdlUEUq")
                .organizationCode("Mu-fBO6eqN-L-W-d----4m6-ee0T")
                .privateMoneyId("1a20781a-b26b-4c77-b596-ae99100b8c66")
                .setModified(true)
                .types(new String[]{"exchange_inflow"})
                .description("1bmU8JxRawwHaJtRxh37Xuv98SeqKvVAk6GXjEud9QeXfkI1B4erbac9yQcn2WojxUQxgGnD");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .customerName("d5W3HpyFNHJAXbgTkkx1ZIZuXSE8SfB9rZ6gOjUGHvRB44FkUS5V1lmXRcSCv8fsZZILuDyzRjrgf6dGbsgwsH4wFGI0ZTwtSTTYZKoNhoybFPHojti1ZgzlpI0KyL72X9nXaOOpvrwY0JwD2grmoqK9oPqcctr9s4xfB76XIBjxmLPXwNN9c5crVlnWSxHAzdbAUwXHqa73TZ1zTw2ElkZR1SAj6T")
                .terminalId("9b3b5004-0dee-40a7-9f50-77c8d42b05cf")
                .transactionId("dY")
                .organizationCode("--3G7G19Mkx5p9orD-I--xNOh-5N-s1")
                .privateMoneyId("3fa7e08a-da0d-4401-8f5b-3e7a67b1b866")
                .setModified(true)
                .types(new String[]{"expire"})
                .description("FLd0HdUvav3w7HfNscUiHg1AWM3oyAi3lhbq8MIwlhHM6yQ71jGguRb48SvfXvDHTsBB1lHe8HIc8u0zwZAl5wOK8hPQnyu4PJ6pXUYqHTeoUe90oz");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test9() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .customerId("416adb86-717d-42ba-a7b0-f266b626bb8a")
                .customerName("GYl2cMfiNX87LNQhDiEl1MzJzSkKqbNdghbdXqZg8tmY1v2nRvQbxXdB8ZEvI21axSU91Q1IlcVtIiGMpDqtfpzYSGwKqKQwzYDX")
                .terminalId("f44f7dba-42a1-4ea8-bf29-890f1505b61b")
                .transactionId("9j")
                .organizationCode("6F1-P1")
                .privateMoneyId("dcceeef7-06d2-4526-a0f3-ccf43db56cff")
                .setModified(false)
                .types(new String[]{"expire"})
                .description("KhnFbeNKITyfuocz9gNyLLuN2E1SL01ewQLmTw");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test10() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .shopId("da02b638-64f3-4e0f-bebc-745397189e22")
                .customerId("af3e52e4-6c86-4faf-b9f9-84aee18f1c50")
                .customerName("pDoZym3DSJNwb0S6KNjpAQOho7jxOtcobKWUZmuKGVUacEq1PoBS804s7pmd9YPzKa2p69hyyblYFyI3irGp96Wi4CaX7ez12ZQ8ZDG8Vx96bVZ7Z9Al9IRwmvpvmCLuflr49EeAufMKTZ5SFPZdnTZ9zoky1Q8mrJeVJNkotCmmqJWmjCfl9BocibLnkfV4A64ZAAIascFZx3CJq1OjTDjcNdiawkisDIkjsASUsQ")
                .terminalId("ff13fad8-512d-4636-882b-f21302ee54de")
                .transactionId("UzvfUbDSA")
                .organizationCode("ars-2N9X-g1SdF--I-k--Qp-wy-XJ")
                .privateMoneyId("054ad09f-dae3-4212-9724-d171a3af5431")
                .setModified(false)
                .types(new String[]{"exchange_outflow","topup","exchange_inflow","payment","cashback"})
                .description("VQDovZKxzYI2sb6Uwm0Wo3yNtalRWKMqfEfBVE3A0LkrtPm0p5gDCqgJvmvTwOzI4nKGPnrQNwc6Fs68UX1XlicdUHcRyWKKkKMdjB5MLnJEwxbWO");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test11() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .perPage(1027)
                .shopId("f5f86e19-3fc0-489c-9962-a7d86173a552")
                .customerId("379c8ddd-bfbb-4e8e-829a-5c9a45d9e829")
                .customerName("Fo7PPmcAtWNmS7u0kWBwYiCL5IK2wW4xc4EExmDmFj2uwmL8a95T765CkSZuYYQkHm4GQ8dPCPJmdJpyKmqZnLUQ44sU1xTRrXRyBrq5wzVPt080eZVO69rCG5y4HU3X8")
                .terminalId("47462100-30d4-477a-890a-562dfcf15970")
                .transactionId("rJk4")
                .organizationCode("Z40ZD-QI-p-sM9-5719---l")
                .privateMoneyId("6805babf-def3-461e-85b0-88336153189e")
                .setModified(false)
                .types(new String[]{"payment","exchange_outflow"})
                .description("xO30sfmZnxf7DIXQvpdCooxe9y8GCZ8SrqikWgV6O8v7jSGCmK7HjzD76o8uS7efrbJQXidAJJqO4EDlEYUAm5nlWdbbpmZi4p9kNkPCubNPsSOKuMS1LjWbH0LzQ");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test12() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .page(2898)
                .perPage(5153)
                .shopId("1b0de968-069d-46f7-98c4-4ef6314616f0")
                .customerId("a5281471-f74a-4006-a107-a7dd33995308")
                .customerName("G8VSkDS6MDCH1ukPTQP5nvFP5dnWqoWPAG5OJStlpPwGDJJ9pVCCfvCqYnHycTL7v8GLk0tGJ2ZD8t")
                .terminalId("c3a5c091-237e-4cbe-afbf-ce7c3de13656")
                .transactionId("eO4hVr")
                .organizationCode("18820--91g2141pLFdu-r")
                .privateMoneyId("5dc5d705-712f-4e6a-b8d8-88340e589307")
                .setModified(true)
                .types(new String[]{"exchange_outflow","cashback","exchange_inflow"})
                .description("FAr0xYgULzkqcSNJ3kPF9QP4PFfHYGyaVWBHn83lhLw1qVBtFQW");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test13() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .to("2021-01-11T06:53:39.000000+09:00")
                .page(3665)
                .perPage(5862)
                .shopId("36a7f109-a6c7-4e31-a2c2-69b694e1b9e5")
                .customerId("e1fb7bd1-d236-40ae-aebf-bfe841a1e8d3")
                .customerName("DfrX2jwG2lJAh7sswZmO5KGRWKgqjFLufosKYqmiZc7ubB9w68PmVyrLPUbbRt05V1P1F9D6gGdQXLZNsx33GiCBapJrvfNMn6m3KCJbo")
                .terminalId("85000b97-c7b9-4e18-be6e-a1c89b15558a")
                .transactionId("B6biFqLxSh")
                .organizationCode("28-6-r78-5v3QTkx")
                .privateMoneyId("44dd8012-a824-4120-bed2-ae36ac74bee0")
                .setModified(false)
                .types(new String[]{"payment","cashback","expire","exchange_outflow","exchange_inflow"})
                .description("btXb53pJ4MfUTT2sXrLJZszLXnCE2WJZRNdmiFtZEblVTYyx2xQIPE8lfOrxsdxxHrk50ZpyFDSHS9V1v2y8V1r8PpA9CX2CAZSjPflNgbc2GNqy2WR8LXWqAKsOwqB4rJNry36AnJRiX2hn5ZjSFwohB");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test14() throws ConnectionError, ProcessingError {
        Request request = new ListTransactions()
                .from("2021-06-03T11:36:50.000000+09:00")
                .to("2022-02-21T21:32:48.000000+09:00")
                .page(1063)
                .perPage(9295)
                .shopId("4a741111-6704-4ede-ba2a-85a52271491f")
                .customerId("32f2a420-cc1d-43f7-9069-5dd1afd9ed8f")
                .customerName("XocCCR9rSDi7v0qxKQSOTlWMizDKFJvsBR63nAx0oivR6ItZTysFnAWWi")
                .terminalId("20611b5e-76b7-44d9-8acc-3bb74ae92fab")
                .transactionId("f3QPiAcV")
                .organizationCode("6G6w866")
                .privateMoneyId("0afffbac-b62e-4e39-aafd-85d5016587ee")
                .setModified(false)
                .types(new String[]{"cashback","exchange_outflow","exchange_inflow"})
                .description("edGgqUoAcJ2YrEgV0MWtW6d2xCNyE1GGfkRmrOYF0QnEvVBvYQauqTuA1M44OPCRJhHbfKiVaOZSN6WnYna379DmGIf45LwBgaAEmMyciQsvFndTQRnnFwz8YuuqGpo6SnKosnsaGLJqwwpGYOfrQGitPTdQsHWxiOQcfbrKelUsXqz");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
