// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.ListShops;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ListShopsTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new ListShops();
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .perPage(5605);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .page(6292)
                .perPage(5463);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .withDisabled(true)
                .page(8252)
                .perPage(7878);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .externalId("K2jzB19RF4Z4NYsp8qZoXKpJ3iRoEb1x")
                .withDisabled(false)
                .page(3173)
                .perPage(9878);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .email("af9YgD7Ka6@h4lJ.com")
                .externalId("mfNk5K5lEMrMHH2BwMiVB")
                .withDisabled(true)
                .page(2758)
                .perPage(9363);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .tel("055-224-026")
                .email("ikLLrQ4Vfi@vIRX.com")
                .externalId("ySnrxWPdsqcIGmEQSLSKO1hRafzt466Tb")
                .withDisabled(true)
                .page(4974)
                .perPage(4373);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .address("IjGxmOtKw8loleZwEXO8vIGAC6wEvhjjeCsMyzWY1EKtNhapbHVL0VrDO628TsdjhrEeYxlhhIjZCqmmlLlrNjmTPwuhCAHa3mQm7bHGOgCh4JFe")
                .tel("01597-2662")
                .email("z8LYTRjl63@Bd1w.com")
                .externalId("3ooBFrXzktBm")
                .withDisabled(true)
                .page(2626)
                .perPage(6939);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .postalCode("265-1683")
                .address("2HawqG98m6Cl3DAtzSHfGD88DtYVjV2cHLUfugSAQQYgzaox0TbTs0UCdR4amKeltgDZU5P0ric1qfv4FNj3QVshPkyAUEEm2WJ2HXE7P3opB7d404r3K2nrqmaf")
                .tel("05-8647-0445")
                .email("f8DAjHEeU1@jxqh.com")
                .externalId("srzypQKPmK5DTpfxmky94zdQwDTvSD")
                .withDisabled(false)
                .page(4066)
                .perPage(8516);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test9() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .name("lDXa6ZR31eXXfqwD6IxncIbUl8Wix4eHlNIzD1rrM8f46nb4eet8uHszVyJmQqr7tgZwL08FCYp5jFH1rqlG05N")
                .postalCode("475-7600")
                .address("gzm92uCf3eE9H5Fs74ANAXSxPyUVJ51ivEGdvqO6tt6JM1kdB3e0iplzGtpfhJ0U4v")
                .tel("02-94-761")
                .email("M5rmGoreTl@ml3A.com")
                .externalId("IfSGkxxNbPRdSHbFruepkmjvvQvZ")
                .withDisabled(false)
                .page(3145)
                .perPage(5522);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test10() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .privateMoneyId("8f8712da-f123-4c70-9267-bea197e8146a")
                .name("FwlFeWwywzT9LWnsda7klcjTF8SaUinVWyXBmPmnjibaOM7zUYFm47nSZW3oBcrmGyrv5rM3Y0VC8X0poRjTn3MItviiTrrrnDqd4kCQ9P5ZOSGewsBlKllvMMVV01Zg79VyRIPzAlrtYrKFywATbn")
                .postalCode("090-3429")
                .address("kzKknzett0OTTC6ptwBJmzyqPciz9KnKLvb20EkHC8cZzJgHQYS9d0fJyqNlv8IPOYRb96Nb1OnTvej8RykNLdjBitMkB79UoMx87LDmSdM40mTtJbbSPOTA9OgcvcwtvT97kWJyNBFLvEv")
                .tel("0063280220")
                .email("RQAVDy54uV@4TwR.com")
                .externalId("VcIGX1lfyXlG4VmlNnNN9dIUtrc9")
                .withDisabled(false)
                .page(7941)
                .perPage(6201);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test11() throws ConnectionError, ProcessingError {
        Request request = new ListShops()
                .organizationCode("zDc-qe")
                .privateMoneyId("f22cfd1d-594d-4e9d-9da8-7c4f238cfb6a")
                .name("KO28TwfI6cIfl")
                .postalCode("3810084")
                .address("cXCH8BtY3SH8hrTk9ivHlawVXrqYV85Hc07YMfhouzr28Onoz94RDDRmcIsmYKA12fqCV60Jpv1mbTWqQ7Dvl8QBADUGOQU5JlHf57A2XmXckHrIKsiM49")
                .tel("038-35-438")
                .email("INpWLuRsRr@Lob1.com")
                .externalId("kcnUl6AfUcGJPl")
                .withDisabled(true)
                .page(1136)
                .perPage(4228);
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
