// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.ListTransfers;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ListTransfersTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers();
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .description("LtjMs9yL76x0ed9uWqZov7iaWjYjGEoKy4C4AL5NDNNnuhrca97lhkjObthD5lzUDMlIgJdP9HzfS3yveLiaON67JLGsG09soG9Wz5Q8LLU1rMyFfZyFofS");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .transferTypes(new String[]{"coupon","exchange","expire","campaign","transfer","cashback","payment","topup"})
                .description("15sJvCYRlUxfunJYJMjJYhpLSoXfNB1GKo6qLNAHufcbfECJqKscom7fsqInS3c2FzdhqxyVP7gd1hFcVBaiyjF221HXrdsfrkoHiz944E66zelswtMDMVLnef1uQCAYFPxbVHHFhG0RjXaAzsQYJHhuFPlMuxKoA6Yypo");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .transactionTypes(new String[]{"transfer","topup","exchange","payment","cashback"})
                .transferTypes(new String[]{"expire","exchange","transfer","topup","cashback","campaign"})
                .description("U1bYpyddfSMrCjcgVQh791Ufpv6c");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .setModified(false)
                .transactionTypes(new String[]{"payment","cashback","exchange","topup","expire","transfer"})
                .transferTypes(new String[]{"exchange","transfer","expire","topup","payment","coupon"})
                .description("VIPLpE0eNAtPWVa3J4GV8PiOvAjZrUFDZC4lzxYwfemIMQqRqVAmMPCM2PoevSoDM28CY3VrBiClurGeSoyCElATbHRbllNC5J8hzqU9YULpbGUsZpMZIyA8UFMaCBuM4Mrg43ypZIkjyrqdKz");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .privateMoneyId("17f38719-1112-453d-8a67-a3d05b371c03")
                .setModified(true)
                .transactionTypes(new String[]{"payment"})
                .transferTypes(new String[]{"transfer","expire","coupon"})
                .description("iID0AM2BshK0L1FZDphjoMfmO6kZ8hvyeenLl5h1z2gkqkQKAf4MSrjYShxFAGCta2hrVGU6NBKGPxWYJF3jQRkcG124vRLE9HQbhjcgH2b5NU1c8KNGcXdI2xVrqbWYJ7yQMRklIzAB9EQ0HgyhNLbNVVcj1CcLStVSIkPzYg");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .transactionId("d0193168-4967-47f8-8a9f-9306cbb761a8")
                .privateMoneyId("ebb0fe4f-509e-49e6-bd05-dcb75caa0a78")
                .setModified(false)
                .transactionTypes(new String[]{"payment","topup","exchange"})
                .transferTypes(new String[]{"topup","coupon","expire","exchange","transfer","payment"})
                .description("0Mu6cwGsD4X5J8F2XEh4zW");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .customerName("yCGTpJlfr30wDFzjNYBqhRtXPduSDQ9eVEaElC6oiaAzWjPKdzzMNGTMpjYOoXj2R7LAxKVK1yYX9p4subiIBjjFVBE3M4T2XCmX5VGYZkJgsOzlmQNwetPATokLBax7ns6RATCtZDPC54SohMxEOKfByUdWvIejrs")
                .transactionId("4dce16f3-82e8-4725-bf24-7dbd60de07ff")
                .privateMoneyId("2ce898fe-163d-4bb4-91df-b2a4ac6b5ce5")
                .setModified(true)
                .transactionTypes(new String[]{"cashback","expire","payment"})
                .transferTypes(new String[]{"topup","payment"})
                .description("KcBvqBI2nlgBTNAVoa1OTERB5Rqg7lfN3rz8C6TQ43Mb1YwDgSJlZ7OBLxbCxA13A0WU5t0TkgsmjGSQpYnfd6j8M1qdCRhr0dDLfwW29hwzetVhrBqPrKEEIz59fNVt2hBOsis1HNS3Oiiu154MHbiF4O4");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .customerId("e6075668-7d6c-436b-aa88-1e4a1d7f8f06")
                .customerName("yenzkveOjXvkizoRAwYri1aqdBIZPzUKhIdcKpJTrzE1a6UGeuT2GPLHVLSuRBxxSNrZDPkowlkSJz9m1KH2QNy6vrVrkaaeLsuEqNLnInvyCIoj0XFuyC7E5n1N2ta2tzSJkym4yqUelBKu2Fi9iORzeBnWx2nHJPI8Y5B6dZP8pts31zo2IcR0b9wJya1xtufPyNnc")
                .transactionId("9d1f81a6-b01e-484d-a4f7-2527cf72b35f")
                .privateMoneyId("1d10fa03-c778-41f6-8cd1-0f6096ff0593")
                .setModified(true)
                .transactionTypes(new String[]{"payment","topup","expire","exchange","cashback"})
                .transferTypes(new String[]{"expire"})
                .description("cvnKMp1tJNTbDMYPhqAVR8fgCtS8YFq5R4");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test9() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .shopName("157AsrEB9zOyZ8rx308fEWoa5uZga0ouFr0uqMmDvDFmpz7N8didfBGcm1jlFItdLGFDupxclcYEv0lkLHBOS1HvzQVMItIQNXLZjb0WusKNAVpu5M7jzkWp2wfEsYKFYnXurKP8h1z22GfYbAYqgmt10V6Yxm")
                .customerId("4ff762f7-3780-4fd4-9234-f54d6c78a9c4")
                .customerName("gZ3rAAMiffJh76H5PGA25hCoqOKUsqSLIFhURyjVq6Q3apy3w8BW5apTj0va7eFOZNl3IHTTgFKtCzQDYkOtvHKZVcbcPN8oIFQlDgps91dP0pPFRis4fsqvSwIJKDexds1iS9iXjexHjrvoljaBafnSwfkIPvtSNnKDOngepygVJl8mZvFKQYAGSrvtjSRvwEKXD8kdRlmTS5Syz")
                .transactionId("fa054e60-239d-44a6-b388-984e25928439")
                .privateMoneyId("f464a003-61c9-47fd-a3a1-2b6c21534c2c")
                .setModified(true)
                .transactionTypes(new String[]{"exchange","cashback","transfer"})
                .transferTypes(new String[]{"coupon","campaign","payment","expire","exchange","cashback","transfer"})
                .description("VB40O7jXqAerShAq15k9");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test10() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .shopId("9314bb2d-23c4-4deb-9414-32ccfa234f34")
                .shopName("dVQrmF1MG0JiF4U4bUzPAI0GwdcMbHRHGfyCYywImQM2KNl8Sd8QjvcE1x5vIKsgEbxPlPtfk4aCLKswhjVeb2FT7kBXiXBLj8DD95tKKrNfl6wxiUe7IjAK0yKp6T7XXQHJXUWp7Exz89gWqRvSdQFEL7tichkKZJJ8ax7I9A6JD3NK74h8Hg4HmbBMr4YFlc6NcP03AZGiUosFMtSE1skfc0jfXB8HoNd6kbpUe2OjESoQ9byusdTH")
                .customerId("06a14d57-a928-448c-bdc2-a9094bdea458")
                .customerName("OUp4JmDPCee8DOFWt3zRYDQYYwZI6N8beth6GLJJ8G7W4ykPv5WgHpM0GogRsFsURAHfsMVPrc0XwpzvtFbhswD1xlKazaz3cp15by26SZvDicYD2Uko1R")
                .transactionId("4a78b63e-6c36-4ad9-8b6c-aa056bd3364f")
                .privateMoneyId("e1ddd48e-12d4-422b-ad34-7fabc2c37316")
                .setModified(false)
                .transactionTypes(new String[]{"cashback","topup","transfer","exchange"})
                .transferTypes(new String[]{"topup","payment","campaign","transfer","coupon"})
                .description("2dackaHpooOqJzdtTj10jutpzeoLCq7MVPI3Xzy1zMDBcUJKrKL8noSpg7glAikjXnKMzSK6SmYnmW7KjrsnWAnbr8uDAqTDgMeIfYeDfasT3V6T5rwyQGBjc2VxCI310Bw3dVPfyzLmwjOmDtbUTaiMGIYGuf7");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test11() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .perPage(7667)
                .shopId("0f70b5a2-f008-4a35-8f20-58a318f58343")
                .shopName("lraUTZc8")
                .customerId("39f092a0-6de3-40d5-9a48-b7ff50d55a58")
                .customerName("bwhcDMsmGhFjw7p1kBIV3aTuW14iiCAbtK48htKIXpt2HAjUcMkscWO5FTuPe2nVy2SArxErpdPrDO")
                .transactionId("01490221-8ee8-4803-a56c-116db2fe8587")
                .privateMoneyId("71570733-ef0b-4bd1-b242-eb0f9148c472")
                .setModified(true)
                .transactionTypes(new String[]{"expire","payment","cashback"})
                .transferTypes(new String[]{"transfer","coupon","payment","topup","exchange","campaign"})
                .description("OusJD7vpQW5VNEXmANosI6Vl1djl4Z4u1CsSxM3thnIe0nQHzbkC98JsLnn2DOelPNwi");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test12() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .page(3315)
                .perPage(3062)
                .shopId("fc118b14-65cd-41f7-a777-77e5d929e3ce")
                .shopName("Vx2MVlmX9JJG2wQYNyNgICREnVLJrt8haluPsgReQBfvctQYCwDAIWgCEyL9GcgsBgAESQ9bKYUO4PraIhOS1aO7LUMxoUoPvGRAItpbqvzjgGsdOG76Bf68DGY9xh6j4aR9dAve99RlGxQHIF30XaWQmsAUoCF5XqjahqH")
                .customerId("274ab86a-64ca-47c8-b845-5bffeb6c1822")
                .customerName("rskev5mdHXYftf5mwCZqXmsvVqSMclL57EE4fCPDo01sLvv6PAMKo0GccnYr5lSQem92akY0")
                .transactionId("947ffcb7-6064-4749-a3e8-ceff7690add4")
                .privateMoneyId("1c454b64-812a-4524-a8c6-7337ba7ab269")
                .setModified(false)
                .transactionTypes(new String[]{"topup","exchange","payment"})
                .transferTypes(new String[]{"cashback","topup","expire","transfer","exchange"})
                .description("4KuiBPKHWgiTLu0F6BYbKNUsfuAWMKrQYk626XNnTyWhuwPeFSkdtmoo7A7Wfb6reepa2yEQJHjRkrO2E6dJnxRB8JBTJpXgtyn6gVyqU7ALYWK1HJp7Rd");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test13() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .to("2021-11-25T14:39:26.000000+09:00")
                .page(1103)
                .perPage(9272)
                .shopId("0db273ef-867d-423c-932b-1347e2635c7f")
                .shopName("PXoYs70SBlUuTbdbUa8S9Im4487LUdsoOthQf3F6saBARrBscZ71C6sQEuMqhc29MsvOmq9UwQd7VFgF6Y6O451zzq2kf3ImjWh9rdivhxQa9tIAvn1njpcbU")
                .customerId("1ab49b03-a84e-4560-92d4-9da7eb55920b")
                .customerName("gRN5p5swMW8CLuqCgpief8pCI9uJKRI2xSNbyw3LeUZHBRBYKq0QzbxyJistaES2PSHnw5mMWtQca5kki57ZUUo2MUg82XWllGWtTcZxAeAESLPE07Qi0jzaj7JQ8ttwz3bnxwtq5QqiI3Mlk4rUH22bNv9rQHkIlIyzjiLoBs2JLESwiHuuNiQ8yrajtMuLLFUnsUZgR7xhfQzXBftvCnLcusYy9m1leWcuC")
                .transactionId("af38bcd7-4908-440d-898c-facbaa8f00fd")
                .privateMoneyId("2f106669-a187-40fd-aae0-927281f84a32")
                .setModified(false)
                .transactionTypes(new String[]{"cashback"})
                .transferTypes(new String[]{"payment","expire","campaign"})
                .description("OQLeVIUEpRnFhhnCzfJgL5n3Wa4uhKemaMRmZyugP3n1KCYnByJnWdFWENPt7EBLRmogOfOurSkicHCbvX17DlsJCl3A");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test14() throws ConnectionError, ProcessingError {
        Request request = new ListTransfers()
                .from("2023-01-07T09:35:47.000000+09:00")
                .to("2022-09-02T23:36:19.000000+09:00")
                .page(6327)
                .perPage(5937)
                .shopId("2a73e9c2-8794-4f89-9549-0b49a3eb42c7")
                .shopName("YDk9VRc8rWwzRMkzfwArand5BDInIgzupdTh0kaw3DJWuhRH5XQfHZLJ6KtjV3a8XoyMPvvh8lYAakFWBCj8AF3xhSJKlxPzGluLZP4tEWkUmIsf9AgUSj4f8IkFzJ9FUWPKhvwLhOvDqzO57r7gILi96nR22RM8V1SAs9xyllFZgbyZflzkAIMm1eIu3IAMPlErP")
                .customerId("6de88620-b273-4a64-a8bd-8316d10eb92b")
                .customerName("8kQzGtELoNAegMr7tJZXciyaNw47VjZkXQ3y")
                .transactionId("fccbef81-c9e0-4a70-bb71-ca1dc89795df")
                .privateMoneyId("928282ba-2fde-4b0f-91dd-75c14a63f3cf")
                .setModified(false)
                .transactionTypes(new String[]{"cashback","transfer"})
                .transferTypes(new String[]{"cashback","coupon","transfer","topup","campaign","payment","exchange"})
                .description("9siAxf39fNVGG3Z275mYrKutggg08lCfPO0b3GXCv92");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
