// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.RefundExternalTransaction;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class RefundExternalTransactionTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new RefundExternalTransaction(
            "900c60da-53ca-4e89-895b-57970e669e78"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new RefundExternalTransaction(
            "900c60da-53ca-4e89-895b-57970e669e78"
        )
                .description("gE0gcrpzpoRmQHQPRxGwJugQi51QViukm4jjyIHq10TNwdExMw9IFTLY6HT8yXqPiARsccRuHjwqAtvFTJsREgXc6zUbvLIJvtO3xgHbW6783rMQUQbKQ1n14AqenHy2cihBah7mNMWNacMruMeP37hqKJBaEo");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
