// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi;

import jp.pokepay.partnerapi.request.UpdateShop;
import jp.pokepay.partnerapi.request.Request;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class UpdateShopTest {
    @Test
    void test0() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        );
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test1() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .status("active");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test2() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .canTopupPrivateMoneyIds(new String[]{"d9faa56c-3dcd-4bf8-8e1f-cbe88e2b493f","7492cd9a-dede-443a-85e1-ff77e71dac84","60ef3daa-2cd1-4f5f-922e-d45f3bcad1b6","cfafd027-14a1-4bb9-b772-c9add347dd84","6379d6f1-cd54-40fd-b59f-7e69f714d80b","c3c4f20f-a24d-4b97-8e39-ec4b22ace995","bcb86bb1-4f1c-4f06-9f0c-43e17cec100c","c44e8a8f-ea00-4dac-9325-8fae3f1fc204"})
                .status("disabled");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test3() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .privateMoneyIds(new String[]{"8b4dfb6b-9fe4-4b77-85ed-30596b10f5ef"})
                .canTopupPrivateMoneyIds(new String[]{"33296082-e63b-4b8c-bc75-7c83483a7933","e4a67355-809b-4ad0-b18e-2eacff790f38","be3ca83e-b760-49d7-b694-3657dd6a6add","b3910af7-cca5-4329-bad4-f0feb7ab06f4","c8985ca6-5984-4fc7-8be6-6837a44f36d3","59e186c2-f252-4383-8cf9-65ed8b86508b","71db02e9-81cb-418c-9e81-e5249ba8cf00","15a5954d-6d09-4ab1-86fe-358c4f302861","f8f15574-e021-470e-b7d8-47bdb9305a77","8bb115de-5ff2-4168-a7b6-19eeda264350"})
                .status("disabled");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test4() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .externalId("HEBiKBz")
                .privateMoneyIds(new String[]{"ecbad38f-c55b-4579-a66f-7a2081d16a19","a1da4f99-b4e7-47e3-a1b2-a9820ff91463","98a095cc-9648-4ef2-a6ee-d6c917b72210","842d076b-a28d-485c-81bb-80df0ba5138b","f51a4317-41e9-4397-81e9-9107beb56c73","1bf66676-3ecb-428c-9ffa-b6bc92ad4b37","98b93d42-85cf-413c-af58-bfd829895d05","54a1614e-b6c4-40f1-bc87-a3e789b40d69"})
                .canTopupPrivateMoneyIds(new String[]{"cd728184-37e3-4267-b18a-9cd13606b34d"})
                .status("active");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test5() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .email("vgDGNHEXoI@08lN.com")
                .externalId("tRcCCwMNddAi8q8UZUC3RA4")
                .privateMoneyIds(new String[]{"9b2accca-4c3b-485c-8942-b1e522de96ce","b20dde49-256d-4386-9a17-660323463aba","307eabb0-b9e9-41cf-ba2e-77aa11b36df6","461a61d6-efd7-45b2-8cc3-0944f0fc7a6a","a2df9abd-4913-488b-a4a6-991877d3f8d8","b57a6792-3cd9-4c81-ab36-6436916e08d0","8da5d7bc-b84c-4393-81b5-d0754c7f88df","df78a9db-6a70-47ee-8384-61473204672d","40dec5d8-f283-4299-b92d-944a59aa0a2e"})
                .canTopupPrivateMoneyIds(new String[]{"b08fdd99-d6f7-4d54-8b2f-7c6cbb5e0c84","c28aa31c-5adc-436e-857a-19847a3c0f81","44857bf8-7ffd-4dff-915e-efd91482ee7c","8a3a72c9-c161-4330-8747-073774009ae2","2e83bd0f-0fa3-4aa6-8580-0cf8b4fd3452","dacd396e-de4b-473a-ab3e-a41c59b44b7b","9c5ea37f-df04-4ac4-9e6f-5724f70dc972","4d383b37-f64e-45c2-9e0f-7652e39ac01d"})
                .status("active");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test6() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .tel("018-4819457")
                .email("wMw0QH6dcr@b4dS.com")
                .externalId("TD25rRsdV7J9bt")
                .privateMoneyIds(new String[]{"c72aeb4d-62e0-4d70-b5c2-eb777b818970","82f4ac8d-911d-4f8e-8f00-4a64dafb1e70","2617d424-5d2f-4d8a-b5fd-de7db62aa234"})
                .canTopupPrivateMoneyIds(new String[]{"d17e231b-9df1-41dc-975b-fc53aacc96e9","4850558d-8532-4cd1-b527-828ed3fcb13c","50df76e9-e4e5-4eae-b78f-87a096a35304","5f18f2c3-331b-45ad-af1c-a1087c27a5b5","34f14b76-3834-4b1d-a3d9-2c8a705cba85","2342e554-d433-4b36-878f-0738b286d2f5","dba66538-ee7a-40de-a0eb-90c613cf2f80","49b7ed74-cdb8-4b52-adf4-ddcf9ba1b3d8","88c432f2-75e7-42eb-b9dc-e38cfbb69ff2","6db799c6-da3c-49a1-8957-eac0092cf69e"})
                .status("disabled");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test7() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .address("jBcC6ZmSUNnzAwxxWqLbsUtRYPkuZ2OS3dS8MdplhUjKpvlZnBSyC6iSSnDVwsYPSzSoHqOVY2rMgb3caHxl0lIfPKUQefSabGzX7rCsl4W9IedwJXwXru80eDpgS0K4bxseKXJ8sdVEeMN6HEkGOWUt0U418zHl5gj96kzujRnPli86ir6cb2ry6J888XdZX690xRrS51l8A")
                .tel("034-26-8371")
                .email("Bvf4qD63vy@GSpL.com")
                .externalId("WX89Nup9r8yDAj6U1CY")
                .privateMoneyIds(new String[]{"35b982bc-a4b2-45f9-be09-9eef96396a28","263e0552-2774-4d8c-a1ea-278b899689fb","7b26536a-4b03-4926-90a7-896b4cfc43ad","fcf5c4cf-a7b5-4920-aeaa-bc43a573703d","5ed74149-2034-49f2-81ed-43ee7e87b40c","1ca75d02-9a42-4bed-8868-36e8a552382c","f177e81e-9a66-4c99-bbfb-cc4b58b5c689","fdc5f104-4234-4cb9-95c2-950bf06275ae"})
                .canTopupPrivateMoneyIds(new String[]{"97454c35-159d-4b43-b723-43ed1b81448a","7ccb04d3-a763-410d-a8f6-5ffab3a32dab","213b8ae7-b218-454f-b07b-d72ed21fd081","ceff74d3-ceb6-4b17-91db-b3e21fb1115e","648f9e89-4990-4015-be2d-24e2da46ec6a","e8a65976-ccb5-4390-a34b-7462b32a5b3e","d5f10e66-ed52-4677-94cd-733544c2250a","9d52bdf8-5945-408c-8832-ddf7552eef6b"})
                .status("disabled");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test8() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .postalCode("4228739")
                .address("gX")
                .tel("0953-1037-2734")
                .email("AzBJw0VUUZ@vUBm.com")
                .externalId("YSCfxf0NSoVXWHlz")
                .privateMoneyIds(new String[]{"f8815fc2-b43f-410a-9967-d0d54e2437a1","2bc7d25f-41ad-4cf7-b180-dcfbc3dafb71","d8c36dd6-e4ef-41f6-b207-0414ea9acd15","6f150481-3629-4d90-b7a0-db93e9db2cc1","7088b71d-1878-4bcc-ae01-db38e16decfe","8216c880-d4df-4179-8914-a906c6c9ff54","29ae4d02-4254-4e7c-bc43-320ad56292d3","4b869f39-666e-45a0-988b-110028af2142"})
                .canTopupPrivateMoneyIds(new String[]{"f4cc39bd-e5fd-40d1-b2d9-02b1bfb1766f"})
                .status("disabled");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
    @Test
    void test9() throws ConnectionError, ProcessingError {
        Request request = new UpdateShop(
            "b4c78f52-401c-4eb5-811d-e7da69771f7d"
        )
                .name("8qExAnQZFJCRGSRxyEE4xjESsZ5ZTG4Ewn2Gh5mogUVbqtX0UvGsiXi5fLxb06pgnQNF7dV96IxOE7WTSi9C6YGh8W0lJPSqxbc8sp1tBKozeGzeXfxFqRRqissUjJt9xCJN4YfocNdlAC61BV1puJwYjN0UptRykVHqbK5y3xuXvMniZfmt4bz0x3hz9enRw7ptwEj3GQlmwU3omNEaQvu697b33s")
                .postalCode("585-6245")
                .address("5yLqwGCyYcqQanceGMGoUS09hp1E3w3A0xDLxHv0EpSUfnf5GXFyCvT4l2sSbvmy1L2vVo1Na8SEthyZyWTo7AEAdYUE8I4V8uttLsvcEC7LQOITHhgLHZeTX6jt3tLk3KudAF5w1LXr1QzEtKdlvHBG8xp2o944hcBSkb0244O58CA1aLomhuCShVDRMJdQ6MBjmHIyQ7HHcDlOjvFuAOhgT1q0lW6nWuSgBPPuLepZgxUy")
                .tel("05043017")
                .email("J5ZSEiSd8w@9rZB.com")
                .externalId("7MFmJOVo0hDRtRvDsLNDEyttAcc")
                .privateMoneyIds(new String[]{"307f95fa-db3e-4eb7-9139-d950b0ff9ca0"})
                .canTopupPrivateMoneyIds(new String[]{"a892fbb4-4654-4959-a462-df9c42a75445","88249ac5-b1be-4e86-903a-f303cc72c500","dc852e46-b1cc-4167-8052-cbe092cb2882"})
                .status("active");
        try {
            PartnerAPITest.getClient().send(request);
        } catch (PartnerRequestError e) {
            if (e.getType().equals("invalid_parameters")) {
                System.out.println(e.getType());
                System.out.println(e.getMessage());
                System.out.println(e.getRawJson());
            }
            assertNotEquals("invalid_parameters", e.getType());
        }
    }
}
