// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.request;

import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import jp.pokepay.partnerapi.response.*;
import java.lang.reflect.Type;

public class CreateBankTopupTransaction extends Request {
    private String privateMoneyId;
    private Integer amount;
    private String bankId;
    private String requestId;
    private String userDeviceId;

    public CreateBankTopupTransaction(String userDeviceId, String privateMoneyId, int amount, String bankId, String requestId) {
        this.userDeviceId = userDeviceId;
        this.privateMoneyId = privateMoneyId;
        this.amount = amount;
        this.bankId = bankId;
        this.requestId = requestId;
    }

    @Override
    public Method method() {
        return Method.POST;
    }

    @Override
    public String path() {
        return "/user-devices" + "/" + this.userDeviceId + "/banks" + "/topup";
    }

    @Override
    public Type getResponseClass() {
        return TransactionDetail.class;
    }

    @Override
    public JsonObject getRequestBodyJsonObject(JsonSerializationContext context) {
        JsonObject object = new JsonObject();
        if (privateMoneyId != null) { object.add("private_money_id", context.serialize(this.privateMoneyId)); }
        if (amount != null) { object.add("amount", context.serialize(this.amount)); }
        if (bankId != null) { object.add("bank_id", context.serialize(this.bankId)); }
        if (requestId != null) { object.add("request_id", context.serialize(this.requestId)); }
        return object;
    }
}
