// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.request;

import jp.pokepay.partnerapi.response.*;
import java.lang.reflect.Type;

public class CreateCheck extends Request {
    private Double moneyAmount;
    private Double pointAmount;
    private String accountId;
    private String description;
    private Boolean isOnetime;
    private Integer usageLimit;
    private String expiresAt;
    private String pointExpiresAt;
    private Integer pointExpiresInDays;
    private String bearPointAccount;

    public CreateCheck(String accountId) {
        this.accountId = accountId;
    }

    public CreateCheck moneyAmount(double moneyAmount) {
        this.moneyAmount = moneyAmount;
        return this;
    }

    public CreateCheck pointAmount(double pointAmount) {
        this.pointAmount = pointAmount;
        return this;
    }

    public CreateCheck description(String description) {
        this.description = description;
        return this;
    }

    public CreateCheck setOnetime(boolean onetime) {
        isOnetime = onetime;
        return this;
    }

    public CreateCheck usageLimit(int usageLimit) {
        this.usageLimit = usageLimit;
        return this;
    }

    public CreateCheck expiresAt(String expiresAt) {
        this.expiresAt = expiresAt;
        return this;
    }

    public CreateCheck pointExpiresAt(String pointExpiresAt) {
        this.pointExpiresAt = pointExpiresAt;
        return this;
    }

    public CreateCheck pointExpiresInDays(int pointExpiresInDays) {
        this.pointExpiresInDays = pointExpiresInDays;
        return this;
    }

    public CreateCheck bearPointAccount(String bearPointAccount) {
        this.bearPointAccount = bearPointAccount;
        return this;
    }

    @Override
    public Method method() {
        return Method.POST;
    }

    @Override
    public String path() {
        return "/checks";
    }

    @Override
    public Type getResponseClass() {
        return Check.class;
    }
}
