// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.partnerapi.request;

import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import jp.pokepay.partnerapi.response.*;
import java.lang.reflect.Type;

public class ListWebhooks extends Request {
    private Integer page;
    private Integer perPage;

    public ListWebhooks() {
    }

    public ListWebhooks page(Integer page) {
        this.page = page;
        return this;
    }

    public ListWebhooks perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    public Method method() {
        return Method.GET;
    }

    @Override
    public String path() {
        return "/webhooks";
    }

    @Override
    public Type getResponseClass() {
        return PaginatedOrganizationWorkerTaskWebhook.class;
    }

    @Override
    public JsonObject getRequestBodyJsonObject(JsonSerializationContext context) {
        JsonObject object = new JsonObject();
        if (page != null) { object.add("page", context.serialize(this.page)); }
        if (perPage != null) { object.add("per_page", context.serialize(this.perPage)); }
        return object;
    }
}
