name: release PR

on:
  push:
    branches:
      - release/*
      - cxxxr-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          gh pr create -B master -t ${{ github.ref }} -b ''
